### ISSUE TITLE
Funding - how to receive and how to generate?

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#10]
My thinking is along these lines

- We leverage everything we can to make as much PPE equipment that is acceptable to the medical profession as quickly as we can.

- This includes 3D printing, laser-cutting, foam building with human beans and whatever else we can do.

- We want as much throughput as possible to provide as much PPE as possible as soon as possible within a 1-2 week timeframe which is when we expect NHS occupancy to peak.

- As a bare minimum we need to prep the consumables pipeline to get in what we need to manufacture before we need it.

- It looks like we'll be ready to be scaling up manufacture in a few days.

So it seems timely to start thinking about how we pay for the things we need to pay for.

That seems to require some kind of setup to receive money and do appropriate accounting things to ensure everything is transparent and we can't be criticised for misusing funds etc.

How would we do this? Who can take pole on this?

**Comment by afroleft** [comment]
@ajlennon reaching out to a friend who’s former Ernst & Young accounting who maybe able to run the checks and balances. 

Will follow up

**Comment by JackiePease** [comment]
intubationbox.com site has a way of donating money, we could do this and / or crowd funder of some type, or PayPal?

**Comment by ajlennon** [comment]
Also relates to #1

**Comment by afroleft** [comment]
> @ajlennon reaching out to a friend who’s former Ernst & Young accounting who maybe able to run the checks and balances.

@ajlennon he's happy to help 👍🏼

What's the best way forward? Set him up on here? In Slack etc?

**Comment by ajlennon** [comment]
Wonderful. Can you give him my email and number. If you can give me his email I'll get him on our Covid19 local Slack channel (unless you want to!)

**Comment by ajlennon** [comment]
I've reluctantly returned to Facebook. It is asking me if I want to setup a fundraiser. That seems a good idea. Can your finance guy have a think about that @afroleft ?

https://www.facebook.com/DoESLiverpool/posts/2413707958729672?notif_id=1585503828912208&notif_t=story_reshare

**Comment by amcewen** [comment]
I think as well as cash for materials we should also be looking to pay the [Living Wage](https://www.livingwage.org.uk/) (or similar?) to the people we end up enlisting to run laser-cutters, box up kit, do deliveries, etc.  Lots of the people who'll offer help and whose laser-cutters we'll be enlisting to scale up are freelancers rather than institutions with existing funding.

**Comment by afroleft** [comment]
Shooting in the dark but want to get this funding ball rolling, please guide me. 

We know that we want around: 

`£2000` for a palette’s worth of materials, PETG in particular [Link](https://github.com/DoESLiverpool/covid19/issues/7#issuecomment-606043201) //cc @KarlDunkerley 

Guessing `£500` for consumables. 

---

### How many people do we think we’ll need? 

Some ideas, based on:
* 4 weeks of production + fulfilment
* Based on living wage [[Link]](https://www.livingwage.org.uk/)

2 laser cutting Assistants 
`£2,796.80`

1 person Goods Out for boxing / cleaning / printing stickers / dispatching / delivery coordination
`£1,398.40`

1 person full time deliveries—can support Goods Out in Down time 
`£1,398.40`

---

### Round about 

Materials = `~£2500.00`
Labour = `£5,593.60`
Buffer = `£500.00`

Total = `£ 8,593.60`

We could have a crack at Crowd Funding `£8000.00` to get the ball rolling.

Other quick options:

1. High net worths 
2. Quick release grants 
3. ... bank?

---

### Linking with Procurement 

Once we have a supply to hand, my hope is that we link directly with hospital procurement teams who will be able to draw us up a Purchase Order to cover our costs.

Have been linked with UCLH procurement and East Lancs, so will try and add some clarity here. 

Please add thoughts, want to get this to a conclusion asap.

**Comment by KarlDunkerley** [comment]
Does this help? using Acetate not PetG.
PETG pallet load give 28,000 masks but needs cutting down to A4.


    On Monday, 30 March 2020, 18:00:27 BST, Tom Darlow <notifications@github.com> wrote:  
 
 


Shooting in the dark but want to get this funding ball rolling, please guide me.

We know that we want around:

£2000 for a palette’s worth of materials, PETG in particular Link //cc @KarlDunkerley

Guessing £500 for consumables.

How many people do we think we’ll need?

Some ideas, based on:
   
   - 4 weeks of production + fulfilment
   - Based on living wage [Link]

2 laser cutting Assistants
£2,796.80

1 person Goods Out for boxing / cleaning / printing stickers / dispatching / delivery coordination
£1,398.40

1 person full time deliveries—can support Goods Out in Down time
£1,398.40

Round about

Materials = ~£2500.00
Labour = £5,593.60
Buffer = £500.00

Total = £ 8,593.60

We could have a crack at Crowd Funding £8000.00 to get the ball rolling.

Other quick options:
   
   - High net worths
   - Quick release grants
   - ... bank?

Linking with Procurement

Once we have a supply to hand, my hope is that we link directly with hospital procurement teams who will be able to draw us up a Purchase Order to cover our costs.

Have been linked with UCLH procurement and East Lancs, so will try and add some clarity here.

Please add thoughts, want to get this to a conclusion asap.

**Comment by KarlDunkerley** [comment]
![MK III Costings](https://user-images.githubusercontent.com/34492815/77951416-eeddf680-72c1-11ea-8e9d-d22eee645fef.PNG)

**Comment by KarlDunkerley** [comment]
Alex, Ade, I have someone in Bootle who can cut the rolls down for me.

Am meeting him at 4.30 tomorrow.

Is there anyone who can bring other roll over and meet me there to get it cut down as well?

Cheers.

**Comment by DoESsean** [comment]
It wouldn't be a huge amount in the grand scheme of things, but is Awesome Liverpool still running? A £500 grant would certainly be a decent start.

**Comment by afroleft** [comment]
> A £500 grant would certainly be a decent start.

@DoESsean lovely!

**Comment by KarlDunkerley** [comment]
I've already spent that out of my own pocket. can make over a thousand but would appreciate support for future amounts. any thoughts?
Also need volunteers to ramp up production.
BTW Warrington Fablab now delivering to Warrington NHS....
Fab Lab Warrington

**Comment by ajlennon** [comment]
I've just bought 5 x 3D printers. I'm not necessarily expecting to get that back but on the off-chance the money is recoverable I think we should make sure that expense receipts are sent onto @mjamjoum

**Comment by mjamjoum** [comment]
My contact info is mazen.jamjoum@hotmail.com for all finance related things.

**Comment by KarlDunkerley** [comment]
I should have the materials and equipment for over 1,000-2,000 visors by weekend. 
Can someone advise on how we productionise this?
Keen to get started.
Five people could start a production chain for efficiency.
Thoughts anyone?


    On Tuesday, 31 March 2020, 11:20:21 BST, Alex Lennon <notifications@github.com> wrote:  
 
 


I've just bought 5 x 3D printers. I'm not necessarily expecting to get that back but on the off-chance the money is recoverable I think we should make sure that expense receipts are sent onto @mjamjoum

**Comment by ajlennon** [comment]
Had this through. Slightly tangential to the PPE effort but worth considering. @afroleft 

> Hi Alex,
> 
>  
> 
> This may be of some use to you.
> 
> Requests for Business Intelligence and Assistance
> 
> New technology challenge to support people who are isolating
> 
> £500,000 of funding is available for technology companies who come up with digital support solutions for people who need to stay at home because of coronavirus. Funding of up to £25,000 per company is available. For more information on the programme and how to apply, visit techforce19.uk.
> 
>  
> 
> Kind regards
> 
> Kath

**Comment by epsaul** [comment]
Hi all,
been watching your progress from Lock-down in the Wirral. Have you seen this grant? It should be available to you through the Innovate UK route:
https://www.ukri.org/funding/funding-opportunities/ukri-open-call-for-research-and-innovation-ideas-to-address-covid-19/
All the best.
Ed.

**Comment by ajlennon** [comment]
Thanks @epsaul will pursue that grant angle

**Comment by martimorta** [comment]
Hi,
I have seen this other grant from the government 

https://apply-for-innovation-funding.service.gov.uk/competition/583/overview

> You can claim 100% of your project costs up to the maximum of £50,000. These will be paid in advance of the project start date.

I hope it helps,
cheers.
Martí
