### ISSUE TITLE
Request proceed/end decision on improvised frames project

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#100]
I have made a visor screen according to the Flemming specification. My observations are:

- It works. It produces a visor that appears fit for purposed and is reasonably comfortable for me.
- The visor screen plastic is very fragile and is not suitable for this design without the addition of relief holes at the end of all cuts. I had to use a lot of 'support' (staples and tape) to hold the finished visor together.
- i do not believe a person can make a suitable visor without additional tools like a hole punch, and a jig would be needed to do it efficiently.
- Assembly is a little more tricky than the Prusa design and marginally more tricky than our laser cut design.

In summary, to proceed with this project we either need to decide laser cut time or a die will be allocated to making the visor frames. Or, get a suitable tool like a punch, do some more testing, with the understanding that if it is successful the frames will be cut by hand. I need to know if this is considered worthwhile or not.

The visor is in the large back room, please feel free to test it. The original design was too long so I cut it shorter. It is now probably a little too short and would be made longer.

![20200426_164705](https://user-images.githubusercontent.com/20521565/80312829-70e90e80-87df-11ea-8f30-8767a93cea28.jpg)

![20200426_164738](https://user-images.githubusercontent.com/20521565/80312835-747c9580-87df-11ea-9118-56151a07b5e0.jpg)

**Comment by drakard** [comment]
@JackiePease @amcewen could you please tell me how volunteer / laser cutter / 3d print time allocation is decided? As explained above I feel this project would need one of these to complete. Otherwise I will let the supplier know DoES are unable to implement this project unless they could provide a better attachment options on their frame design.

**Comment by JackiePease** [comment]
No problem in doing some samples. Then I think it would depend on the demand for each type

**Comment by drakard** [comment]
Ok I will make a design for the laser cutter and get a punch.

**Comment by drakard** [comment]
Flemming have sent me a new, simpler design for the visor shield which should have less chance of tearing. It will still need manual punching probably with a jig. I will make a  sample.

**Comment by drakard** [comment]
As a new design is being provided I am closing this issue, at least until the new design has been evaluated.

**Comment by drakard** [comment]
Flemings tried out the new clip based design. It was much simpler but sadly it looks like the clips might not be secure enough for a long period of use. Tom from Flemings suggested we could use a dot of glue on each clip or double sided tape. That would require us to assemble them before delivery or have the users assemble them. I am reopening this issue because I would like to know is that feasible.

**Comment by drakard** [comment]
After speaking with other members the consensus appears to be that sticking the visors together with glue or tape either before or after delivery is not suitable. Because demand for visors appear to be starting to subside I advised Felmings that it is probably not necessary to continue this project.
