### ISSUE TITLE
More high capacity bags for laser cutter plastic offcuts

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#102]
We have filled the nice large heavy duty clear plastic waste bags with laser cut offcuts for reuse / recycling. Now we are using regular bin bags. These are not ideal as they are smaller and also can rip from the sharp plastic. Depending on whether it would be worth the cost, it would be nice to have some more of the large high quality bags.

**Comment by drakard** [comment]
If the previous bags are too expensive it would be good to have high capacity regular bin bags for this.

**Comment by plastictactics** [comment]
If the laser operator is prepared to cut them into strips I can supply 
boxes and take the plastic in batches - maybe we could trial one to see if 
this is workable?

**Comment by drakard** [comment]
That sounds good to me. The standard practice is already to cut the waste into strips. I'm certainly happy to put into boxes when I'm operating.

**Comment by drakard** [comment]
@JackiePease gave me some of the heavy duty bags which I have put into the laser room.
