### ISSUE TITLE
Is old laser cutter height tool still valid

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#103]
The yellow laser cutter height tool has been added to the laser cutter keyring. I was told that since it was fixed the laser cutter has a different focal height. Also a new square tool was made. Presumably that means the old tool is now incorrect.

If the old tool is wrong I think it should be thrown away or it can only cause confusion. Would the people who fixed the machine be able to confirm if the old tool is no longer valid?

**Comment by JackiePease** [comment]
It isn't valid at the moment, you can put it in the cupboard in the laser room

**Comment by drakard** [comment]
The old tool was put in the cupboard with the keys for the thrown away locks.
