### ISSUE TITLE
Supply visors in Africa

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#106]
@plastictactics how much would 100 sets of DoES visor frames and bands cost please?

**Comment by plastictactics** [comment]
Hi, this question has surprised me a bit so please bear with. We haven't been selling them - just providing a cutting service for this project. Have you mistaken me for the sales role of this project, or are you looking for a separate quote?

**Comment by drakard** [comment]
Hi @plastictactics most of the laser cut visor frames are dirty and need cleaning, but I noticed some came clean from being cut. I spoke to some people and they thought the clean ones came from you. I would like to start looking into supplying some visors to Africa with some of my friends from Africa so I was hoping to buy 100 sets from your company as a sample.

**Comment by amcewen** [comment]
@drakard presumably you'll want the clear plastic parts too?  Maybe (given our order book is slimming down now - anyone who knows someone who wants visors should definitely request some) stick a "request visors" submission to [visors.doesliverpool.com](https://visors.doesliverpool.com) with a note that you'd like @plastictactics frames, and then we can include it in the rest of the system easily.

**Comment by drakard** [comment]
@amcewen thank you, that is super kind. I have put a request in for 100 in the form.

**Comment by drakard** [comment]
Ah I didn't mention @plastictactics :/

**Comment by drakard** [comment]
In addition to the 100 DoES design visors I discussed, I am also sending 100 injection moulded Prusa visors. These need to be provided with laser cut bands. @plastictactics , would I be able to also purchase each of the attached part designs from you? I would need 100 of each type for the sample.
[Visor adjuster band dxf.zip](https://github.com/DoESLiverpool/covid19/files/4606538/Visor.adjuster.band.dxf.zip)

**Comment by drakard** [comment]
@plastictactics  do you have any idea if you would be able to make those bands?

**Comment by plastictactics** [comment]
I have them in stock - call me to arrange collection

**Comment by drakard** [comment]
@plastictactics The parts in this zip file are the "bands" to replace elastic on a Prusa type visor, which you can see in #98

**Comment by drakard** [comment]
The cost of commercial laser cutting with @plastictactics is too great relative to the unit cost of the other parts unfortunately. I will look for other options.

**Comment by drakard** [comment]
@JackiePease I think you mentioned to me someone who had been mass producing die cut parts? Would you be able to give me their contact details?

**Comment by JackiePease** [comment]
Contact details provided to @drakard

**Comment by drakard** [comment]
Thank you Jackie!

**Comment by drakard** [comment]
I haven't been able to find a supplier to provide the bands for the Prusa type at a price I can afford. I would like to avoid elastic if at all possible. I know the laser cutter is already in great need at the moment, but would it be possible for me to cut 100 sets on it? That would allow me to finish the 100 sample Prusa visors I have already. They are small that should be only 1 or 2 sheets. I'd be super happy to come in at a time when there aren't any volunteers running it. If that is possible, could you please let me know what that would cost? I looked here https://doesliverpool.com/services/ but I wasn't sure. Would that be the workshop cost?

**Comment by drakard** [comment]
My band designs fit on the offcuts from the main visor manufacture, so I'd be happy to buy those instead of full sheets.

**Comment by JackiePease** [comment]
Workshop charge is £6 per half day, plus £2 surcharge to use Gerald. This page tells you how to book:  https://github.com/DoESLiverpool/somebody-should/wiki/LaserCutting#bookingOn 19 May 2020 11:00, drakard <notifications@github.com> wrote:
I haven't been able to find a supplier to provide the bands for the Prusa type at a price I can afford. I would like to avoid elastic if at all possible. I know the laser cutter is already in great need at the moment, but would it be possible for me to cut 100 sets on it? That would allow me to finish the 100 sample Prusa visors I have already. They are small that should be only 1 or 2 sheets. If that is possible, could you please let me know what that would cost? I looked here https://doesliverpool.com/services/ but I wasn't sure. Would that be the workshop cost?

**Comment by drakard** [comment]
@JackiePease Thank you. I don't see anyone volunteering on the laser cutter tomorrow morning so I will come in then (I booked). I can also do some cutting once I'm finished : ) . Is it ok for me to use/buy the polypropylene offcuts?

**Comment by JackiePease** [comment]
No problem with you using some of the offcuts
________________________________

**Comment by drakard** [comment]
The visors have been sent to Nigeria for testing. Thank you for the help with this.
