### ISSUE TITLE
Wrap-up Video: A thank you from DoES to our donors 

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#108]
As the Visors Project draws to a close we thought it would make sense to wrap up with a little thank you video. We’ll share with all of the donors on GoFundMe and on the social places to let them know where their money went. 

Appreciate we face constraints; distancing, availability, not to mention locations (our finances are being managed in London and our comms in Warwick).

## The plan:
* On our selfie camera’s (in portrait mode) we’ll all record ourselves saying our nominated word below
* Once done, send to me with the number and your name in the description https://www.dropbox.com/request/frFUbNdP9AmfqIkgVpDc
* I’m a no editor, but I’ll give it my best shot to pull them together into a little 1min long video
* I will update as videos come in
* ⭕️ = vacant - I have left these open on purpose for you to invite people who you think will be good to jump
* It will only take a second to put some makeup on and record this. No excuses
* ⚠️ **Final DATE FOR SUBMISSION Friday 15th, 6pm** 

Here’s a proposal for the script with some nominations:

1. ✅ Hello (@hannahforbes)
2. We (The couple that were meant to get married! @JackiePease do you know if we can contact them?)
3. Are (@zarino )
4. ✅ The Team (@ajlennon )
5. ✅ Behind The (@mjamjoum)
6. DoES  (@amcewen )
7. Liverpool (@JackiePease )
8. ✅ Visors (@KarlDunkerley )
9. Project (@plastictactics)
10. ✅ In Total (@afroleft )
11. We Produced (Chris Huffee)
12. ✅ 24,000 (@jackreason85)
13. 100 and ⭕️ (Dave Coffee?)
14. 20 ⭕️
15. ✅ 6 (@afroleft)
16. Protective visors (@amcewen Holding a visor)
17. For ⭕️
18. ✅ Critical need (@ajlennon )
19. ✅ Healthcare workers (@DoESsean )
20. Across the Northwest 
21. Thank you (thumbs up 👍 ) ⭕️
22. So Much ⭕️
23. ✅ For helping us to (@MatthewCroughan )
24. Help ⭕️
25. Them ⭕️

**Comment by zarino** [comment]
Quick tip for recording this – I’d ask each "actor" to record not just the single word/phrase they’ve been assigned, but also the entire sentence.

If they say the sentence slightly slower than they normally would, with a slight stop between each word, it’ll be super easy for us to edit, and it’ll sound more natural once edited (compared to twenty people each shouting one individual word) – plus it gives us the opportunity to pick different people for different words, after the fact.

**Comment by KarlDunkerley** [comment]
Sounds good.

**Comment by zarino** [comment]
PS. "We produced […] protective visors to critical need health workers" doesn’t make sense. You can "produce visors _for_", or you can "_send_ visors to", but I’m not sure you can "produce… to".

**Comment by zarino** [comment]
PPS. @afroleft I’m happy to edit all of these into a single video, if you need someone else to do it.

**Comment by ajlennon** [comment]
Here you go... [AlexTeamThankyou.zip](https://github.com/DoESLiverpool/covid19/files/4615013/AlexTeamThankyou.zip)

**Comment by afroleft** [comment]
> PS. "We produced […] protective visors to critical need health workers" doesn’t make sense. You can "produce visors for", or you can "send visors to", but I’m not sure you can "produce… to".

dyslexia 1 - tomo 0 😅

> Quick tip for recording this – I’d ask each "actor" to record not just the single word/phrase they’ve been assigned, but also the entire sentence.

Good idea - let's do that. Glad you have more opinions than I do about this. 

> Here you go... AlexTeamThankyou.zip

Cheers @ajlennon -- Can you do this:

> Once done, send to me with the number and your name in the description https://www.dropbox.com/request/frFUbNdP9AmfqIkgVpDc

**Comment by ajlennon** [comment]
> Cheers @ajlennon -- Can you do this:

Done

**Comment by hannah-forbes** [comment]
Done! Did the whole sentence as @zarino suggested. Excited to see the full video!

**Comment by ajlennon** [comment]
Oh a video? ooooook

**Comment by afroleft** [comment]
> Done! Did the whole sentence as @zarino suggested. Excited to see the full video!

@hannahforbes perfect, thank you!

**Comment by afroleft** [comment]
@amcewen would Irene be up for doing one for us?

**Comment by JackiePease** [comment]
I'll ask her now
________________________________

**Comment by ajlennon** [comment]
Video uploaded

**Comment by afroleft** [comment]
@ajlennon thank you ! 

Heads up all, tomorrow eve is the deadline. Please let me know if you do not want to participate, I can reorganise the sections.

**Comment by KarlDunkerley** [comment]
Still up for it. Will try to do this morning when I've woken up properly!!
    On Thursday, 14 May 2020, 06:53:51 BST, Tom Darlow <notifications@github.com> wrote:  
 
 


@ajlennon thank you !

Heads up all, tomorrow eve is the deadline. Please let me know if you do not want to participate, I can reorganise the sections.

**Comment by KarlDunkerley** [comment]
Hi,
Long time no see.
Can you send me your version of the sentence so I can record it this morning?
Cheers,


    On Tuesday, 12 May 2020, 11:39:59 BST, Zarino Zappia <notifications@github.com> wrote:  
 
 


PS. "We produced […] protective visors to critical need health workers" doesn’t make sense. You can "produce visors for", or you can "send visors", but I’m not sure you can "produce… to".

**Comment by afroleft** [comment]
Thank you: 

@jackreason85
@DoESsean 
Mazen !

@KarlDunkerley go here you will see the sentence we are reading out https://github.com/DoESLiverpool/covid19/issues/108#issue-616546853

**Comment by afroleft** [comment]
Thank you @KarlDunkerley !

Just @zarino @plastictactics @MatthewCroughan @amcewen @JackiePease to go. 

> Please let me know if you do not want to participate, I can reorganise the sections.

**Comment by MatthewCroughan** [comment]
@afroleft Recording the whole speech so you can snip the parts you want from me now. Will upload in a minute.

**Comment by MatthewCroughan** [comment]
Scrap that, I couldn't remember the whole thing and couldn't figure out how to record in the background, so to get it done quick just said a few words before, I've uploaded it :)

**Comment by afroleft** [comment]
> Scrap that, I couldn't remember the whole thing and couldn't figure out how to record in the background, so to get it done quick just said a few words before, I've uploaded it :)

Bingo👍🏼

**Comment by afroleft** [comment]
Thank you to everyone that submitted videos, you all look lovely. 

I made this using video tutorial software so it's not where I'd like it to be, but it is something: https://twitter.com/afroleft/status/1262013335282778112?s=21

Here's the original, go ahead and share on your networks: https://www.dropbox.com/s/9f0b18szvdnnptx/DoES%20Thank%20you%20to%20Donors.mp4?dl=0

Will send this out to our donors.

That's about it from me on the comms side for now folks. 

Hannah will follow up with Jackie about handing over the social media accounts.

**Comment by zarino** [comment]
Oh poop, sorry @afroleft, I didn‘t realise you needed an edited video so soon! @JackiePease sent me a few clips directly via WhatsApp – did you get those too?

**Comment by KarlDunkerley** [comment]
Love the video. Can I download it from somewhere?

    On Sunday, 17 May 2020, 15:28:36 BST, Zarino Zappia <notifications@github.com> wrote:  
 
 


Oh poop, sorry @afroleft, I didn‘t realise you needed an edited video so soon! @JackiePease sent me a few clips directly via WhatsApp – did you get those too?

**Comment by afroleft** [comment]
>  Love the video. Can I download it from somewhere?

Yes @KarlDunkerley — can you see it / download it from here? Let me know if you get stuck https://www.dropbox.com/s/9f0b18szvdnnptx/DoES%20Thank%20you%20to%20Donors.mp4?dl=0
