### ISSUE TITLE
Find out if any local hospitals would want an "Intubation Box"

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/covid19#12]
Via Naomi Wu on Twitter: this sits "over the head and shoulders of a patient as they are intubated by a [health care] provider. The box acts as a protective shield between the patient and medical staff ... can be cleaned with bleach or alcohol solution in betweeen patients":
 https://intubationbox.com/

**Comment by amcewen** [comment]
Via [@AlyssaAlabassi](https://twitter.com/AlyssaAlabassi) [here's an interesting Twitter thread of UK medics discussing it](https://twitter.com/rupert_pearse/status/1244279557059776512) (mixed opinions on how useful it would be)

**Comment by plastictactics** [comment]
Closed on the basis that the jury is out on the usefulness of the product, the assumption that @JackReason85 has not received requests for something like this, and that we're plenty busy with the visors for now.
