### ISSUE TITLE
Investigate mask designs

### ISSUE THREAD

**Issue by JackiePease** [DoESLiverpool/covid19#13]
As mentioned in the readme, it seems diy masks can provide some protection, and are also in short supply. Some seem to have space for filters (don't know if these are readily available either). We might be able to provide these to others, or might be useful to people working on our project.

**Comment by amcewen** [comment]
Sadly @ajlennon has provided more detail in his new identical issue #17, so while I'd rather close his as a duplicate, it's more prudent to close this one
