### ISSUE TITLE
Spanish design twists in use when printed at 0.3mm layer height

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#14]
When trying on the latest prints of the Spanish design, using their 0.3mm layer height option, it twists *lots*.  I wasn't sure if that was me pulling them off the printer too quickly or something, so left them to cool today and it's no better. 

![TwistedVisor](https://user-images.githubusercontent.com/108468/77824608-d02e0300-70fb-11ea-816e-1e33fb90d33d.png)

I didn't see that problem in the one I printed at 0.2mm layer height, but maybe I got lucky...

**Comment by JackiePease** [comment]
@KarlDunkerley and I both found that the Spanish design dug in at the sides, and twisted slightly.
For me, the Werkstan one was more comfortable and didn't twist - the cutouts make it more flexible, although might also make it slightly less effective in stopping virus getting in from the top.

**Comment by amcewen** [comment]
I think this means we've decided not to go any further with this design, so don't need to resolve the twisting problem.
