### ISSUE TITLE
Decide which designs we're going to produce

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#15]
We're learning a reasonable amount about different designs, and trialling them.  We'll need to work out what is acceptable to the *local* NHS services that we'll be delivering to.  It would also be good to discount any designs that we've worked out we *won't* be producing (e.g. the Spanish design is looking less likely due to #14 but we haven't done much testing of *any* of the designs yet).

**Comment by amcewen** [comment]
@KarlDunkerley has some samples of the Spanish, Verkstan, Prusa and my laser-cut polyprop design, and some visors from our thin polyester.

He'll be seeing some friends who are medics, so hopefully will be able to report back their opinions.

**Comment by ajlennon** [comment]
Had this through from Alyssa Alabassi (surgeon) for review

[https://groups.google.com/forum/#!topic/london-hack-space/41uNwWcPnPk](https://groups.google.com/forum/#!topic/london-hack-space/41uNwWcPnPk)

**Comment by ajlennon** [comment]
@wyn_griffiths who I think is working with North Wales Tech has just posted this *brilliant* design improvement

>Currently working on stacking of the Verkstan design for higher yields overnight. Bridging is the keyCrossed fingers

![image](https://user-images.githubusercontent.com/1537834/77831869-a390e000-7129-11ea-921e-a870e45a5cf2.png)

ref: [https://twitter.com/wyn_griffith/status/1243981565513863168?s=20](https://twitter.com/wyn_griffith/status/1243981565513863168?s=20)

**Comment by JackiePease** [comment]
There's an STL with stacking Prusa visors too. At the moment it has 2 stacks of 4 which doesn't fit on the Ultimaker bed. I'm hoping @mdunschen will edit it to remove one of the stacks.

**Comment by ajlennon** [comment]
Have you seen these stacking ideas @MatthewCroughan ?

**Comment by mdunschen** [comment]
I'll get onto it tomorrow, sorry only seen this now. It's a great idea the
stacking.

**Comment by amcewen** [comment]
The stacked Prusa print worked nicely, thanks for the file mod @mdunschen!  (Although I've not separated them out into individual visors yet - will try to do that tomorrow).

As discussed in #14, we're dropping the Spanish design from our consideration now.

The covid-19 slack has settled on the Prusa RC3 as its chosen design; Liverpool Uni is using a slightly modded version of that; in the discussion call earlier with the PPE experts there was a strong preference for designs that kept the visor further away from the face... all of which point to using the Prusa RC3 as our preferred 3D printed option.  I think we'll just be printing them from now on.

And alongside that we'll do the laser-cut and Karl's foam design.

**Comment by amcewen** [comment]
The stacked Prusa comes apart pretty easily.
