### ISSUE TITLE
Standardize visor hole spacing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#16]
The Verkstan design has a different hole spacing to the Spanish, Prusa, and my laser-cut design.  Having two different visor hole spacings is going to cause no end of problems, so we should standardize on one.

The Liverpool Uni design seems based on the Prusa one, so once we've got one of them printed to compare, we probably need to mod the Verkstan design (or maybe pick the right option - there are a few with different hole spacings, but the one we're printing *seems* like it's already the nearest to what we'd want)

**Comment by ajlennon** [comment]
I'm sorting out my 3D printers now. Should I start printing one of the designs today or wait until we have something with standardised hole spacing? If I should start printing now what is the advice on what design I should use at present?

**Comment by amcewen** [comment]
@magman2112 could you print out this file (on paper) and see if it lines up with your 4-hole punch?

[Template-shield-EUROPE-4hole.pdf](https://github.com/DoESLiverpool/covid19/files/4397570/Template-shield-EUROPE-4hole.pdf)

**Comment by amcewen** [comment]
@ajlennon Can you print out one of the Liverpool Uni design?  And maybe a Prusa alongside it to see if the hole spacing is the same on them both (I'm guessing yes, but it'd be good to confirm, and also good to be getting a couple of the LU design printed for testing/comparison)

**Comment by ajlennon** [comment]
Will do boss!

**Comment by amcewen** [comment]
There's a [4-hole version of the Verkstan](https://github.com/Cederb/Faceshield.nu/tree/master/Europe/3D%20Printing%20Files%20(STL)) available.  I'm printing one out on Prints Adam at the moment to see what it's like.

**Comment by amcewen** [comment]
The 4-hole Verkstan version matches the hole pattern all of the other designs are using, so let's standardize on that.

@magman2112 it'd be nice to know about the 4-hole punch lining up, as that'll help us with production, although we can easily use a 2-hole punch twice (on the "888" setting on the ones we've got here)

@ajlennon reopen this if the Liverpool Uni version *doesn't* match the Prusa for hole-spacing.  Otherwise, I'm declaring this issue resolved!

**Comment by magman2112** [comment]
Sorry to take so long, but my main PC which has my printer attached has decided to pick today to fall over, so no printing for the moment.

I did test the punches though, I have now found 2, and the hole spacing is 80mm from centre to centre.

**Comment by JackiePease** [comment]
The Prusa has a different hole spacing to the Spanish, 4 hole Verkstan and laser cut design

**Comment by drakard** [comment]
In today's meeting between Fab Lab Warrington and DoES I believe we tentatively standardised on the Prusa spacing which is (79mm/80mm) - 60mm - (79mm/80mm) centre to centre. This is not the same as the 4 hole punch spacing which is 80mm - 80mm - 80mm. The Prusa spacing is used by Covid Volunteers UK and we tentatively believe also University of Liverpool.

**Comment by drakard** [comment]
What list of stakeholders do we need confirmation from to move this to closed?

**Comment by amcewen** [comment]
Agreed @drakard, it looks like we're settled on the Prusa spacing.  Liverpool Uni are using that too.  I'll need to update the design of the laser-cut option for the new spacing (and we might want to modify or find the right Verkstan file too, if we're going to print any of those - but that's looking less likely now).

Once I've updated the laser-cut file, I reckon this can be closed.

**Comment by huffeec** [comment]
I've been looking at the laser cut version today but it's still not completely clear which hole spacing to go with for this.

The Prusa spacings are more widely used in the 3d printed designs, but without building a jig it's not as easy for us to make the face shields for these designs. We can laser cut them but that ties up the machines that could be making the headbands. (and probably need the staining cleaned before use.)

The advantage of the 4 hole punch is we, and more importantly hospitals, can easily make replacement shields from A4 acetate. So headbands can be reused with replacements made locally from readily available stock. 

So I think we could get out the 4 hole design more quickly and hospitals could make their own replacements, but the Prusa seems to be a more widely adopted standard.

There's no obvious best choice, but would appreciate input from others before I start cutting materials.

I've added versions of @amcewen 's design with both spacing's to the repo.

**Comment by amcewen** [comment]
I like the 4-hole approach, given its ease for us to produce and the ease of explaining to hospitals how they can make their own.

The only downside of it is that the 3DCrowd folk are just supplying the Prusa design, and so also the Prusa spacing, and it'd be nice not to have two competing standards in hospitals.

I had tended towards the Prusa spacing, *but* we couldn't work out a simple way of explaining to anyone how to use a two-hole punch to make the spacings (with the other odd-spaced 3DVerkstan design you can punch the holes really easily just by setting your two-hole punch to A6 and doing it twice, but there doesn't seem a similar approach with the Prusa spacing)

Which I think is me coming down in favour of the four-hole spacing too.  I think @JackiePease, @ajlennon, @huffeec and I will all be in DoES tomorrow morning so we can make a final choice then.  (so get your opinions in before then... :-)

**Comment by amcewen** [comment]
We've standardized on the four-hole spacing, and that's what's been in production.  For the handful of Prusa frames we print we can make the associated visors as and when needed.

**Comment by ajlennon** [comment]
Can somebody confirm to me that the current visor shield design is not compatible with the Prusa RC3. 

I need to get a Prusa RC3 laser cut design provided to 3rd parties (SMEs and education sector) as we can provide them with bulk die-cut visor shields of half mill poly

I am told the NHS prefers this. Plus it's cheaper.

Assuming the Hybrid V1 design is what we are using and that this isn't compatible with the Prusa spacing can we modify this @huffeec ?

Also I am seeing comms. about small bed printers (which I suspect some educational establishments may have). Will this design be workable for them too?

Thanks.

**Comment by huffeec** [comment]
There are 4 hole (80,80,80mm) and Prusa (80,60,80mm) versions of Adrian's original design and the V0.5 kitronik design here [https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/README.md](https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/README.md)

There isn't a Prusa version of our Hybrid design anywhere AFAIK because by that point in our designing we'd settled on the 4 hole.

The largest dimension of the Hybrid V1 is 380mm people working with smaller cutters have created versions of the Kitronik design that fit. I think this is Prusa(80,60,80) but haven't made any so can't confirm. There isn't currently a version of Hybrid V1 in this format because it wasn't needed for the machines we are using.

**Comment by amcewen** [comment]
Our current visor design is not compatible with the Prusa RC3.  Neither is the Kitronik design.  The Prusa uses a really weird spacing that I don't know how to produce easily with either a 2-hole or a 4-hole punch, so it's difficult for hospitals to manufacture their own clear plastic part.

We have enough material for >6500 clear visors at present, and have cut >1000 of the frames with our 4-hole-punch standard.

Now is not the time to change that.  @ajlennon, if you want a 3Dcrowd compatible design (I assume that's where this request is coming from) then spin up a new issue and make it **super-clear** that this is for outside of the DoES Liverpool production efforts.  I don't want you to derail our production system just as it's getting going, please.

**Comment by ajlennon** [comment]
>Now is not the time to change that. @ajlennon, if you want a 3Dcrowd compatible design (I assume that's where this request is coming from) then spin up a new issue and make it super-clear that this is for outside of the DoES Liverpool production efforts. I don't want you to derail our production system just as it's getting going, please.

That's what I'll do
