### ISSUE TITLE
Capturing PPE requests

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#18]
I have a number of email threads about the local need for PPE. 

Some trusts are actually quite well provided for at the moment (Alder Hey) but others are in dire straights (Aintree). There are also many other health professionals and health workers in dire straights including GPs and hostels.

I am increasingly seeing contacts such as this:

>We approached a manufacturer that we have worked with before  in Glasgow to produce 3500 for us. We are getting about 350 a day from them. We have also placed an order from a repurposed clear plastic box factory in China for 50000 that should arrive in 2 weeks. We have made masks out of overhead acetates, foam and elasticed ribbon - but we are only using this for our staff training scenarios (we are getting through 150 per day). We are a small hospital  with only 300 beds so you can do the calculations from there. When we have significant numbers of covid patients - then I would estimate using 600 per day (unless we clean and reuse). The numbers required are massive.

I've suggested that I work with some healthcare professionals to put up a Google Sheet to start to capture the local demand.

Thoughts?

**Comment by ajlennon** [comment]
I've created a prototype sheet here. It needs work. If you want edit access contact me

https://docs.google.com/spreadsheets/d/1I5WjnniUB4E4HEEGh5qVsbhZGgHcBmAEhtuqapLlkfs/edit#gid=0

**Comment by ajlennon** [comment]
@afroleft had an excellent idea about replacing a spreadsheet with a more accessible form we could send out...

**Comment by afroleft** [comment]
Happy to pick this up @ajlennon — Will follow up.

**Comment by tomalrussell** [comment]
We're putting together some aggregation of supply and demand needs over in https://www.helpfulengineering.org/volunteer/ (#project-uk-distribution slack channel). All welcome. 

Let us know if your form/sheet can be linked - appreciate the value of working locally too.

**Comment by ajlennon** [comment]
@tomalrussell thanks for engaging with us! I am on Helpful Engineering. We put a phase two project application in on Friday

ref: https://docs.google.com/document/d/1edP_js_qHgL57S_6JvaYwVUFfh2x-DbDntAcT4gygls/edit?usp=sharing

We have a presence on the UK Covid19 Slack too and have setup a local channel to manage comms. for the NW. covid-19volunteersuk.slack.com channel is #znorthwestuk

We're very keen to engage with Helpful Engineering and Covid19 and not to duplicate effort. 

@afroleft will no doubt be in touch on forms.

Please keep us in the loop @tomalrussell

**Comment by afroleft** [comment]
Kindly @Moorst is going to help us make this form. 

### A proposal: 

We use something like Google forms or Typeform. 

Ask for the following:  

* Your first/last name 
* Your email 
* Which organisation do you work for? 
    * select from list —so we can identify group orders
    * Or other text box 
* What address would you like to have the visors delivered? 
* As we rely on donations to cover material and transportation, can you let us know if your organisation is able to either cover the cost of materials or donate via our X campaign to help cover this request?
* Anything else you’d like to tell us? 
* Last but not least, what’s your phone number?

**Comment by ajlennon** [comment]
Looks great - one thing I will throw in is that we're thinking there is a difference between masks we can deliver to the NHS and masks that are acceptable to community workers. Might be worth capturing that difference from those registering a need?

**Comment by Moorst** [comment]
I've put a first draft together in Google Forms; https://forms.gle/roPzR5cJBceVvSBF6.

I believe @afroleft is collating a list of organisations that can be dropped in when ready.

Can also add in a visor variant option @ajlennon  if we know the types we went to have them choose from.

Let me know if we need any other adjustments, and I can pass on collabator privileges the whomever needs them.

**Comment by ajlennon** [comment]
Looks great @Moorst - will need to liaise with @JackiePease and @amcewen

**Comment by afroleft** [comment]
@Moorst we have the list of Trusts in the North West: 

### North Western

Manchester University NHS foundation trust 
Salford Royal NHS Foundation Trust 
Stockport NHS foundation trust 
Pennine Acute Hospitals NHS Trust—> now part of northern Care alliance with Salford 
Tameside and Glossop NHS Foundation Trust 
Bolton NHS foundation Trust 
East Lancashire NHS Trust
Lancashire Teaching Hospitals NHS foundation trust
University Hospitals of Morecombe Bay
Blackpool Teaching Hospitals NHS Foundation Trust

### Mersey

East Cheshire NHS Trust 
The Royal Liverpool and Broadgreen University Hospitals
St. Helens and Knowsley teaching hospitals NHS Trust 
Aintree university hospital
The Walton centre nhs trust
Southport and ormskirk hospitals nhs trust 
Countess of Chester NHS Foundation Hospital 
Alderney Children’s Hospital NHS Foundation Trust
Wirral University Teaching Hospitals NHS Foundation Trusts
Mid Cheshire Hospitals NHS Foundation Trusts
Warrington and Halton Hospitals NHS Foundation Trust
Wrightington, WIgan and Leigh NHS Foundation Trust  

Is this Google From going to be able to do a App Sheets style `if Other` show text field?

**Comment by ajlennon** [comment]
On the need

‘I’m losing the will to live, god help us all’: despair of NHS procurement chief"

https://www.hsj.co.uk/im-losing-the-will-to-live-god-help-us-all-despair-of-nhs-procurement-chief/7027266.article

**Comment by Moorst** [comment]
Yes, there's an Other field available. Added in those Trusts, same link will show any updates.

**Comment by afroleft** [comment]
@ajlennon and @amcewen I have no visibility of where we are standing on the production front, so for now I am directing urgent requests from the north west down to central [3dcrowd](http://3dcrowd.uk). 

@Moorst has kindly pulled us together a request spreadsheet with a form [(link)](https://forms.gle/roPzR5cJBceVvSBF6) that we can direct people to once we're ready to start fulfilment.

**Comment by ajlennon** [comment]
Capturing orders and PPE need here

https://docs.google.com/spreadsheets/d/1vMMz2R8fOO0pjpU6_j-qK2c9sZiM1R8IxOs_PbNusmI/edit?ts=5e84a3dd#gid=293671453

**Comment by ajlennon** [comment]
We are capturing orders on a Google Sheet. I probably best not post that publically but it's available if you contact me or @afroleft

**Comment by JackReason85** [comment]
@Moorst Hey Chris, is it possible to add another field into the PPE Request form please.

We need to know what their position or role please, with drop down selections;

- CFO
- CEO
- Head of Procurement 
- Directorate Manager
- Assistant Directorate Manager
- Senior Consultant
- Junior Consultant 
- Chief / Lead Nurse
- Staff Nurse
- Office / Ward Manager
- Administrative / Secretaries
- Other

**Comment by JackReason85** [comment]
@Moorst Sorry should have said for the other field, if it can be a please specify field

**Comment by Moorst** [comment]
Added 👍

**Comment by JackReason85** [comment]
Thanks @Moorst just seen it on the last order that came through, all working perfectly :)

**Comment by afroleft** [comment]
@moorst can you add this to help us prioritise the orders we're getting through. Demand is quickly outstripping supply and we want to support critical need first: 

If you work in a Hospital, can you let us know what ward/department you work in?
1. ICU 
2. A&E/Covid ward
3. Medical wards 
4. Other (please specify)

This question would not be (*)required. 

//cc @JackReason85
