### ISSUE TITLE
PPE provision strategy thoughts (makers, SMEs, and importing from China)

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#20]
There are three areas we need to progress urgently  imho:

 1. national local maker communities and makers who can 3D print and laser cut PPE for their local communties

 2. covid clusters to integrate SMEs into provision of PPE

 3. importing goods from China

On (3) I have contacts in China as in my day job we do manufacturing there. My contacts tell me they have PPE there.

I have reached out locally to be told that we can't get anywhere as the Chinese have been "sending empty boxes and ripping us off" and NHS trust purchasing won't buy from anywhere that isn't "gold plated".

I have tried to make the point that we are long past all this and we need somebody with some clout to reach out to the Chinese government, send over some big cargo planes , fill them up and bring them back within a week, possibly with the PPE being distributed by the military here.

I have just been told by a surgeon this is what the French are indeed doing.

>Different countries are sourcing resources differently. France imported 600 million masks from China by establishing an air bridge between the two countries. The first cargo plane scheduled to take off today. Italy got 300 doctors and nurses from China who arrived in Milan a couple of days ago.

ref: https://www.bfmtv.com/economie/14-semaines-de-rotations-600-millions-de-masques-le-colossal-pont-aerien-en-la-france-et-la-chine-1883777.html

**Comment by plastictactics** [comment]
Doing a bit of gardening.

Closing under the impression that @ajlennon has developed (1) and (2) into other issues, mostly involving 3DCrowd collaboration, and deprioritised (3) - I agree gov missed an opportunity not creating air bridge, but for better or for worse that is outside remit of this project.
