### ISSUE TITLE
Solid model of Visor PP, for use on CNC router

### ISSUE THREAD

**Issue by mdunschen** [DoESLiverpool/covid19#23]
Here is a link: https://a360.co/2WOksJn to a solid model I created from visor-pp.dxf by extrusion. It needs more work: The tabs for attaching transparent sheets are missing in extrusion, but exist in sketch. My aim to to add a manufacturing toolpath that could be used on a CNC router.

**Comment by mdunschen** [comment]
I've added a new folder with a 3D design (A Fusion360 file) including toolpath for a 3mm flat bottom tool. If anybody has a router or knows how to use the one in DoES safely, please try it out. I'm ready to help out remotely, ie. design or manufacturing alterations.

**Comment by plastictactics** [comment]
Hi @mdunschen, I would like to close this issuee on the basis that the output of the CNC isn't worth the extra management, training and risk involved in keeping the machine busy, given that the laser cutting is cranking them out with lower skilled labour. I love the CNC, but not for this. Any objections? :)

**Comment by ajlennon** [comment]
I agree re: DoES but I would add we have been contacted by SMEs with CNC machines. If somebody wants to take on talking to them that might be a win

**Comment by drakard** [comment]
2 considerations regarding CNC:
it might be possible to cut many sheets simultaneously (perhaps 20?) if the workpieces can be held properly.
The cut edges may be sharp.

**Comment by mdunschen** [comment]
Happy for you to close.

**Comment by plastictactics** [comment]
> If somebody wants to take on talking to them that might be a win

Agreed that there is an opportunity there, but I suggest that that lack of engagement on this issue to date shows we don't have a volunteer at this time, and I know you are up the wall with higher priorities (good job on CE Marking progress by the way).

> it might be possible to cut many sheets simultaneously (perhaps 20?) if the workpieces can be held properly.
> The cut edges may be sharp.

Definitely possible that multiple sheets could change the equation, but this this sounds like a lot of R&D and discussions to me, which comes at opportunity cost of getting the rest of production running at pace and managing the space safely - see #69.

>Happy for you to close.

Thanks Martin, that's enough justification for me ;)
