### ISSUE TITLE
Decision: Centralise everything vs. Localise vs. bit of both

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#25]
I don't know enough about this to make a call, so putting this to the community. 

In broad strokes, we will need ways to:

1. Secure & distribute funding
2. Source materials 
3. Produce PPE
4. Handle & fulfil requests

Lots of stuff between the bullet points, but these are the big jobs to be done. 

Looks like we have some options about what to do here: 

A) Centralise all of our work with the [3D Crowd](https://www.3dcrowd.uk) with ~1200 members across the UK 
B) Work locally 
C) Mixture of `A` + `B` 

I don't know what C looks like. Maybe we don't need to know and we feel our way through it.

What do you think is best?

Opinions very welcome, want to close this off by tomorrow.

**Comment by amcewen** [comment]
Dunno, my tendency is towards B, with us coordinating with people like 3D Crowd (does that make that an option for C?)

I don't know much about them, beyond them seeming quite 3D-printer-focused (from their signup form).  Surely they're going to need regional hubs anyway, so maybe they can be signposting people towards us too?

**Comment by ajlennon** [comment]
Echoing what @amcewen says I think the 3D printing crowd aren't really seeing the limitations in throughput or the problems getting PPE through to medical professionals.

I'm generally supportive of 3D printing as there are lots of hobby printers about but would be keen not to lose the focus on the laser cutting and outreach to SMEs.

**Comment by ajlennon** [comment]
NB. The two people who setup 3D printing crowd are friends of a friend of mine so I've asked him to reach out to them to connect us up

**Comment by afroleft** [comment]
Seeing a tradeoff that looks a bit like: 

### benefits of central: 

1. Less duplicated effort across all jobs (probable)
2. Sharing best practices 
3. Reduce the chances of order conflicts—where 1 trust, 2 medics, 1 orders centrally, another orders locally, we both fulfil and over supply a particular trust

### benefits of local: 

1. Can move quicker (probably, less stakeholder engagement, focus on our own shit etc)
2. Closer to the problem 
3. Easier to coordinate local fulfilment (rather than piling on a central request/dispatch system)
4. People more likely to donate / fund / support a local effort than a national one?? (highly speculative)

**Comment by JackiePease** [comment]
I think we can still share best practices with others while concentrating on a local solution, and keeping supplies and funding local seems like it would be more responsive (although maybe more work).

We should probably sign up though, as potential users might find us that way.

It seems it would be good for us to publicise laser cut solutions nationally, as there is so much focus on 3dp.
________________________________

**Comment by ajlennon** [comment]
As @JackiePease says - The conversations I'm having all include commentary that there are lots of designs and it's all fragmented.

What @amcewen kicked off with the FaceShield evaluation table with design sources, pictures, BOM, speed, medical signoff etc. seems very important to me as a resource.

Also as we have production process documentation coming for best practice that seems as though it will be a useful resource too.

I am keen to align what we have with what I suspect is happening over at CoVid19 UK Volunteer forum as I suspect they are doing similar, at least with production processes.

**Comment by afroleft** [comment]
We’re leaning towards localised. Please can someone set me up with: 

covid19@doesliverpool.com

Would be helpful to have shared inbox specifically for this project.

**Comment by amcewen** [comment]
It's just covid@doesliverpool.com, but has been live a few days now.
