### ISSUE TITLE
Keeping score

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#26]
Radio 4 interviews this morning suggesting we’re on track for a peak mid April. Plus more healthcare workers dying, lack of PPE looking like a cause. [(link)](https://apple.news/ApPbv6RxwSSSAQUsZHHDOjw) 
 
With this in mind, I wanted to get a handle on where we’re up to.

<img width="1778" alt="Screenshot 2020-03-30 at 11 48 39" src="https://user-images.githubusercontent.com/1761311/77905124-9f75d700-727d-11ea-99b0-616aa9c3e2cb.png">

I've set up a [Github project](https://github.com/DoESLiverpool/covid19/projects/1)—essentially a simple kanban—so we can look at what’s outstanding, what's progress and what's over the line. 

With a bit of prioritisation, we will be able to organise ourselves around the next most important thing to get these things in to the hands of healthcare workers.

Unless there's a good reason not to, I'll jump in on threads to ask where they are up to so that we can get issues over the line/drop one's that don't matter. 

If you think this makes sense, please just drop me a 👍🏼 

Here's the project [(link)](https://github.com/DoESLiverpool/covid19/projects/1)

**Comment by drakard** [comment]
This makes perfect sense to me. It does not appear that currently all the issues relating the visors activity are in this "project". Is there a criteria or reason for that? Is there a procedure or process for adding them? Is there a technical method for linking new issues to this project? Thank you.

**Comment by ajlennon** [comment]
>This makes perfect sense to me. It does not appear that currently all the issues relating the visors activity are in this "project". Is there a criteria or reason for that? Is there a procedure or process for adding them? Is there a technical method for linking new issues to this project? Thank you.

I'm not sure I completely understand but to try to respond DoES is a community and as such issues are created by members of the community when they wish to flag something up.

So each of the issues you see in this repository reflects something that somebody in the community thought needed to be discussed, agreed, acted upon.

Anybody can raise an issue and we encourage you to do so. Please check for an existing issue that addresses what you raise first. Duplicates will be closed.

When commenting on issues you can reference other issues by prefixing those other issue numbers with a hash (#). This leads to the cross issue references you will see.

Does that help answer the question @drakard ?

**Comment by drakard** [comment]
Hi @ajlennon 

Thank you very much for the help. Sorry my question was not very clear. My comment is specifically about this list https://github.com/DoESLiverpool/covid19/projects/1 and how it does not to me seem to include all the issues here https://github.com/DoESLiverpool/covid19/issues that relate to the mask project. Does that make sense?

**Comment by ajlennon** [comment]
>Thank you very much for the help. Sorry my question was not very clear. My comment is specifically about this list https://github.com/DoESLiverpool/covid19/projects/1 and how it does not to me seem to include all the issues here https://github.com/DoESLiverpool/covid19/issues that relate to the mask project. Does that make sense?

Yes, so because of the way that issue raising by community members works it's entirely possible that something will not be harmonised. We rely on individuals such as yourself to flag such problems and contribute to fix them :) Feel free to update/improve what you think is missing!

**Comment by drakard** [comment]
@ajlennon thank you. I don't think I have that capability sadly. But it may not be the most pressing issue.

**Comment by plastictactics** [comment]
@afroleft are you now managing the project on another platform? The Github project has been updated for 2 weeks - does anyone still intend on keeping it alive, or would it be best to remove it, close this issue and reduce confusion?
