### ISSUE TITLE
Buy more 3D printers?

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#27]
There are Creality Ender 3 printers on eBay for £100 - £120.

Is it useful to buy in some printers?

If so are Ender 3 printers big enough for the PPE eye protectors we will make?

@amcewen ?

**Comment by ajlennon** [comment]
Hiya @Sean-anotherone I've got six Ender 3's arrived that I need to get setup. You might be self-isolating but if not completely I was wondering if that's something with which you could help?

![image](https://user-images.githubusercontent.com/1537834/78693884-c1adcb80-78f3-11ea-9bec-95e81988f54b.png)

**Comment by Sean-anotherone** [comment]
Kinda isolating, but also needing something to stop me going stir-crazy...
Where & when?
Sean

    On Tuesday, 7 April 2020, 17:18:42 BST, Alex Lennon <notifications@github.com> wrote:  
 
 


Hiya @Sean-anotherone I've got six Ender 3's arrived that I need to get setup. You might be self-isolating but if not completely I was wondering if that's something with which you could help?

**Comment by ajlennon** [comment]
@Sean-anotherone brill. I'm going to try to be there from 10am as I have a work thing from 10:30. WIll be there until 2pm at least and I am guessing @amcewen will be about
