### ISSUE TITLE
Where to submit external contacts

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#28]
I am currently receiveing external contact of 3 kinds:

- Healthcare providers wanting PPE
- People with 3D printers who want to contribute and can abide by the 3dcrowd.uk / Covid Volunteers UK requirements
- People with 3D printers who want to contribute and cannot abide by the 3dcrowd.uk / Covid Volunteers UK requirements

For each of these groups I would like to know should I direct this to:

- 3dcrowd.uk / Covid Volunteers UK
- 3dcrowd.uk / Covid Volunteers UK and also store the details (option below in addition)
- Store it somewhere in this github
- Make a google sheet and store it there
- Forward the info onto a specific person
- Something else

I believe this is related to #18  but I do not see an authoritative conclusion on there and would like one.

Thanks!

**Comment by ajlennon** [comment]
@afroleft has been directing people to 3dcrowd I believe?

**Comment by drakard** [comment]
Thank you.

So is the consensus that this is the policy - direct healthcare providers to 3dcrowd? For people who can contribute 3d printing is it the same? For those who cannot meet the 3dcrowd standards should they still seek direction there?

**Comment by drakard** [comment]
Looks like this is now the answer https://doesppe.netlify.com/

**Comment by ajlennon** [comment]
Weeeeell - we still need to sort out a few funnies getting them to ppe.doesliverpool.com. There's an SSL cert problem

**Comment by afroleft** [comment]
https://ppe.doesliverpool.com she’s now airborne 👍🏼
