### ISSUE TITLE
Produce gowns?

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#29]
Should we produce gowns now or in future

There is apparent current need:
https://www.hsj.co.uk/im-losing-the-will-to-live-god-help-us-all-despair-of-nhs-procurement-chief/7027266.article

**Comment by afroleft** [comment]
My aunt’s friend has this in motion [(link)](https://www.gofundme.com/f/helping-dress-medics?utm_source=messenger&utm_medium=social&utm_campaign=p_cf+share-flow-1). People from all over producing under this moniker.

If you are able to help out, let me know, and I'll put you in touch.

**Comment by JackiePease** [comment]
I notice Mary Lamb, a costume designer based just up the road from DoES Liverpool on Kempston Street is also doing this: https://m.facebook.com/groups/1823980617678627?view=permalink&id=2812243238852355

**Comment by JackiePease** [comment]
As mentioned in #17, Cathy is working with Mary Lamb on this, so I've given the details of our sewists to her.

Details on Facebook:

https://m.facebook.com/story.php?story_fbid=10221412229284946&id=1526123237

**Comment by afroleft** [comment]
Thanks @JackiePease — am I ok to close this issue down now?

**Comment by JackiePease** [comment]
Yes, I think we can close this - if there's anything we can help them with we can open issues then
