### ISSUE TITLE
Add a section to the FaceShield.md file about suppliers, etc.?

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#3]
In [the original issue](https://github.com/DoESLiverpool/somebody-should/issues/1415) @karldunkerley did some good digging out possible suppliers and prices.  We should stick them somewhere - a new section in [FaceSheild.md](https://github.com/DoESLiverpool/covid19/blob/master/FaceShield.md)?

And then we can extend that as we go along.

**Comment by KarlDunkerley** [comment]
Link not working for me. Damn.

**Comment by ajlennon** [comment]
The posts I made have disappeared. What gives ???

**Comment by plastictactics** [comment]
Closed on understanding that this type of information is being managed in the PPE Suppliers spreadsheet.
