### ISSUE TITLE
How to contribute to the project information

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#30]
I would like to contribute to the information in this project.

(For example, I feel it could be helpful to add this mask design https://www.protohaven.org/proto-shield/ to a list of laser cuttable designs, not evaluated).

I notice there is collaborative information in the "code" and the wiki. I can't edit the "code" or the wiki.

- Is it preferred to use the "code" or the wiki?
- How should I / other contributors request access / suggest changes?

Thank you!

**Comment by plastictactics** [comment]
Hi @drakard.

I am also now looking to get edit access for a similar reason.

I'm under the impression that most people are using the code over the wiki. There is also plenty of content in issue discussions that might be better moved elsewhere, but this takes time which current contributors don't have.

As I understand it, to edit either the code or the wiki we need to be added as contributors. I have been speaking to @huffeec who is a contributor but can't add new people.

@amcewen Could you add me and @drakard as contributors? Or would it be better for us to submit pull requests?

**Comment by amcewen** [comment]
@drakard @plastictactics you should both have invites to the @DoESLiverpool organisation, which will then give you access to this repo (and our other public ones too).  You should get an email for it, but if it doesn't make it through you should be able to accept the invite if you go to the [DoESLiverpool github page](https://github.com/DoESLiverpool)
