### ISSUE TITLE
🎨 Identity Proposal: DoES PPE

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#33]
We're all leaning towards a local strategy vs. linking with other UK wide movements. You can see the discussion here Link. 

With this, we need a bunch of things; bank account, our own accountant, our own funding programme and distribution channels. 

@ajlennon mentioned that we can't use the DoES account because it's a CIC etc. No drama, I have a former EY accountant working to set us up a bank account for this project. 

Question for me is identity. Since most people here organise around DoES, I'm proposing an identity for the project: DoES PPE. 

![DoES PPE Landing](https://user-images.githubusercontent.com/1761311/78012686-3f466a00-733d-11ea-83c5-d46d6434c015.png)

Knocked out a quick logo and landing page design. 

I can set up a group email something like doesppe@gmail. 

Can I get your thoughts? 👍🏼👎🏼 ?

**Comment by JackiePease** [comment]
There's a logo on the video - probably easiest to use thatOn 31 Mar 2020 10:51, Tom Darlow <notifications@github.com> wrote:

We're all leaning towards a local strategy vs. linking with other UK wide movements. You can see the discussion here Link.

With this, we need a bunch of things; bank account, our own accountant, our own funding programme and distribution channels.

@ajlennon mentioned that we can't use the DoES account because it's a CIC etc. No drama, I have a former EY accountant working to set us up a bank account for this project.

Question for me is identity. Since most people here organise around DoES, I'm proposing an identity for the project: DoES PPE.



Knocked out a quick logo and landing page design.

I can set up a group email something like doesppe@gmail.

Can I get your thoughts? 👍🏼👎🏼 ?

**Comment by amcewen** [comment]
@afroleft I think we could use the DoES bank account.  We've done similar in the past for projects.  We'd need to keep @DoESsean in the loop so we track the amounts in and out.  We'd need to okay it with the @DoESLiverpool/directors, but I asked the others yesterday and they're happy for that if we want it.

**Comment by ajlennon** [comment]
>@ajlennon mentioned that we can't use the DoES account because it's a CIC etc. No drama, I have a former EY accountant working to set us up a bank account for this project.

@afroleft  I think there's confusion if I wrote that. I actually meant we _should_ use DoES as it is a CIC :)

**Comment by DoESsean** [comment]
It's probably worth checking with the accountants as well, as this is
likely to be a much larger amount of money than we've received in the past
for project costs.

I'll drop them an email today.

**Comment by amcewen** [comment]
The DoES Liverpool logo if you need it is [kept somewhere-safe](https://github.com/DoESLiverpool/somewhere-safe/blob/master/logos/DoESLiverpool.svg) :-)

@johnmckerrell has set up covid@doesliverpool.com, pointing at @afroleft, @ajlennon, @JackiePease and me (at the moment, we can add/remove as need be)

**Comment by ajlennon** [comment]
Here's the editied video @amcewen and I shot yesterday. @MatthewCroughan has done a great done editing and I'm about to get it out. I like his idents at start and end

[https://nextcloud.gamecu.be/s/NnTaCkwtsNSXSGX](https://nextcloud.gamecu.be/s/NnTaCkwtsNSXSGX)

**Comment by afroleft** [comment]
@amcewen @DoESsean @ajlennon I was under the impression we needed an accountant to run this for us but Sean mentioned:

> It's probably worth checking with the accountants as well, as this is likely to be a much larger amount of money than we've received in the past for project costs.

Do we still need the help of Mazen, who's kicked this off [(link)](https://github.com/DoESLiverpool/covid19/issues/32)

**Comment by ajlennon** [comment]
fwiw my opinion is that the DoES accountants are paid to handle the DoES day to day commercials but this is a different thing that needs a single point of focus from somebody with a financial background who is also involved with the team to make sure we're doing everything right and transparently taking in and disbursing monies

**Comment by afroleft** [comment]
@ajlennon @JackiePease just jumped off the phone with Adrian. 

I'm going to pull together a landing page for this project. i.e. [Link](https://github.com/DoESLiverpool/covid19/issues/33#issue-590959983)

I need @johnmckerrell to setup a subdomain on DoES for me. 

`ppe.doesliverpool.com` looks sensible. 

Can you help John?

**Comment by johnmckerrell** [comment]
@afroleft can do, where should it point? I've created a separate issue #34

**Comment by ajlennon** [comment]
Guys - I will assume ppe.doesliverpool.com is the landing page then and ask @MatthewCroughan to make that change in the video

**Comment by afroleft** [comment]
> Guys - I will assume ppe.doesliverpool.com is the landing page then

works for me. 

@johnmckerrell — Im thinking of sticking this on Netlify or Guthub Pages. Gonna need till this evening to turn this around, so will nudge you then.

> I've created a separate issue #34

Perfect 👌

**Comment by MatthewCroughan** [comment]
This is amazing work. @afroleft If you need me to make any videos, transitions or add those graphics you have produced to anything in motion, let me know and I'll get on it.

**Comment by afroleft** [comment]
thanks @MatthewCroughan — deffo want to capture some footage of the production and dispatch to healthcare workers. 

That would give prospective donors more confidence in donating to us.

**Comment by MatthewCroughan** [comment]
@ajlennon Can we work on the previous comment from Tom? I'm all set up now to do more intense, responsive and rapid editing, I've set up my workstation at DoES to transcode into a format (prores) that allows for better performance when editing so that I can get things done a lot faster than I previously could.

**Comment by ajlennon** [comment]
Yeah - I'm at home at the moment though :)

**Comment by MatthewCroughan** [comment]
@ajlennon I mean in the coming days and weeks. 

We'll need footage of:
 - Multiple 3d printers in action
 - People processing items
 - Dispatching of the items
 - Hygiene procedures
 - Planning and documentation occurring 
    - For example. An over the shoulder of Adrian planning out a page on github, at his desk.
    - Paper work printed off that shows a guide for procedures

Stuff like that. If anyone thinks of more scenarios and footage that would be good to add, perhaps we should make a new issue to store it.

**Comment by ajlennon** [comment]
Let's do it !

**Comment by afroleft** [comment]
@MatthewCroughan what you set out here looks great. [Link](https://github.com/DoESLiverpool/covid19/issues/33#issuecomment-606868446)

Can we open a new issue for it so that we can close this one off?

**Comment by MatthewCroughan** [comment]
@afroleft Done, close at your leisure. :+1:
