### ISSUE TITLE
DoES PPE Website 

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#35]
Spent this afternoon pulling this together --> https://doesppe.netlify.com 

`Job to be done:` Give me a way to find out more about what you’re working on, `so I can` find out how I can help.

This is essentially a sign post landing page that we can send every one.

⚠️ Please don't share this URL. Going to coordinate with @johnmckerrell to get `ppe.doesliverpool.com` up shortly. 

We need to add @ajlennon’s video that he shot with Matthew. As soon as it's up on Vimeo, give me the link and I'll add it. 

The website’s source is hosted in DoES GitHub incase I get hit by the ~bus~ virus. 

This is just a first swing, things we want to add: 

* Background, why are we doing this?
* Progress, what have we shipped? Any success stories?
* Press links
* Corporate donation package 
* Social media links
* Our GoFundMe campaign once she is up (working on a Pitch tomorrow first thing, will stick in here for review)

Hit me with your feedback

**Comment by ajlennon** [comment]
Love it! :clap: :clap: :clap: 

So we have the video up on YouTube here - https://www.youtube.com/watch?v=bqUujrXShUQ

Do you need a different copy ?

**Comment by afroleft** [comment]
> So we have the video up on YouTube here - https://www.youtube.com/watch?v=bqUujrXShUQ

That's up now @ajlennon 🚀 

As soon as McKerrell jumps on #34 we can share the love.

**Comment by zarino** [comment]
> This is just a first swing, things we want to add:
> 
> * Background, why are we doing this?
> * Progress, what have we shipped? Any success stories?
> * Press links
> * Corporate donation package
> * Social media links
> * Our GoFundMe campaign once she is up (working on a Pitch tomorrow first thing, will stick in here for review)

@ajlennon @amcewen or @JackiePease – if you have time to take point on drafting some content under these headings, then I’m happy to take it, tidy it up (if necessary), and add it to [the website](https://github.com/DoESLiverpool/ppewebsite).

**Comment by afroleft** [comment]
@zarino could reuse some of this #36 assuming no one thinks is shit ?

**Comment by ajlennon** [comment]
Also some content from my copywriter friend @BrendanReid. He's happy to build daily social engagement by providing copy

> YOU CAN’T BE ‘SOCIALLY DISTANT’ FROM A PATIENT YOU’RE TRYING TO SAVE.
> 
> Our NHS is the last line of defence that we all rely on. Their heroic work saves thousands of lives every day and their tireless work ethic means that no patient is ever turned away; no patient is ever ignored. Now though, the health service faces its toughest challenge yet. The staff who are trying to save us are actually being killed. By us. That’s no exaggeration. Vital protective equipment has not been deployed as it should have been and even if it had, there’s not enough to go around. The NHS is already chronically understaffed and if we infect those taking care of us, we have nowhere else to turn.
> 
> That’s why a group of us at DoES Liverpool are dedicating our time, resources and equipment to producing PPE for the NHS. Our efforts aside, it’s the donations of others that have made a huge difference. We are able to source materials, produce PPE and connect small scale manufacturers directly with healthcare workers and with hospital procurement teams across the North West. All of this is providing a little light at the end of the tunnel but make no mistake, there is still so, so much more to do. 
> 
> With Coronavirus cases set to reach their peak in the next two to three weeks, and the horrific precedents of China, Italy and Spain in front of us, there is no more time to lose. We may have lost too much already but that is precisely why we need to fight on with renewed vigour and we want you to join us. We are all in this together and only together can we beat it.
> 
> So please, go to this link (link) now and donate whatever you can spare to give our health workers the protection they so badly need. After all, the life it saves might be yours.
>

**Comment by zarino** [comment]
FYI I’ve updated the wiki to mention the new website: https://github.com/DoESLiverpool/covid19/wiki/What-we-know-so-far

**Comment by zarino** [comment]
Website now includes all the info from the crowdfunder page:

https://ppe.doesliverpool.com/

So I’d say, out of @afroleft’s original list, we’ve done:

* ~~Background, why are we doing this?~~
* ~~Progress, what have we shipped? Any success stories?~~ (no success stories yet!)
* Press links
* Corporate donation package
* Social media links
* ~~Our GoFundMe campaign once she is up~~

**Comment by afroleft** [comment]
@zarino you are a gem
