### ISSUE TITLE
DoES PPE — GoFundMe Pitch 

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#36]
No one really followed up with me about the fund we'd need to get this started. 

So thinking of rounding off at `£10,000` target. 

Give us money to do things like I set out here [(link)](https://github.com/DoESLiverpool/covid19/issues/10#issuecomment-606120584)

---

# DoES PPE — GoFundMe 

We’re working with hopsitals in the Liverpool City Region to produce effective, low-cost visors, to help healthcare professionals keep doing their job throughout this crisis.

But to really ramp up production, we need your help and your donations.

## A growing problem
Healthcare workers across the country are putting themselves and patients at significant risk of the covid 19 infection because of the lack of protective equipment (commonly referred to as PPE). 

Lack of PPE related deaths are beginning to rack up. Link, Link and Link.

If this continues, hospital wards will become dangerously under-staffed, as infected healthcare workers are forced into self-isolation to protect the public.

Lots of hospitals are reporting huge increases in their consumption of PPE. We’ve heard from a number of concerned procurement teams—the people responsible for sourcing things for healthcare organisation—that they think they will run out soon.

## Rolling our sleeves up to help out… 
At DoES PPE, we’ve spun up a project to tackle this problem; starting with producing protective visors for healthcare workers right across the North West UK. 

### Some highlights: 

* A number of NHS doctors from different specialities have contributed to the visor designs.
* We have designs that enable us to accelerate production using laser cutters (x10 faster than 3D Printing).
* We have the production facilities at DoES Liverpool, and the broad network of makers in our community, to really ramp up the supply of PPE items.
* We’re connected with clinical directors at Alder Hey—one of the largest children’s hospitals in the UK—who will help us distribute PPE across the region. 
* Liverpool Heart & Chest Hospital, East Lancs and Manchester Clinical Communion Groups are also in touch with us for PPE supply.

## We need your help
To help us buy:
* The materials we need
* Maintain the machinery we use 
* Package and deliver the items to hospitals and independent healthcare workers
* Pay a modest living wage to the people working through day and night on this  

We need your help. Any help is a help. 

All donations go to one important cause; getting essential PPE in to the hands of healthcare workers who are risking their lives to save yours.

**Comment by afroleft** [comment]
Live https://www.gofundme.com/f/get-visors-into-the-hands-of-healthcare-workers

Zarino jumping in there and course correcting my horrendous grammar

**Comment by zarino** [comment]
@afroleft I‘ve updated the gofundme content to match the content further up this ticket.

Shall we consider this ticket closed, and open new ones for next steps, like promoting the crowdfunder?

**Comment by afroleft** [comment]
> Shall we consider this ticket closed, and open new ones for next steps, like promoting the crowdfunder?

Great idea X

**Comment by zarino** [comment]
FYI I’ve added a link to the crowdfunder on the wiki – https://github.com/DoESLiverpool/covid19/wiki/What-we-know-so-far
