### ISSUE TITLE
Create an army of volunteers to make PPE visors by hand

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#37]
@KarlDunkerley, Adam Floyd and others have been coming up with exceptional "no print/cut" designs which could in my understanding be assembled by hand by volunteers.

From talking to Karl if it takes 5 minutes to make a visor then 

- one person can make 200 visors a day (say)
- 100 people can make 20,000 visors a day.

[Edit: if we can hit Karl's expectation of 2 mins we may be looking at]

- one person can make 30 / hour => 240 visors a day (say)
- 100 people can make 24,000 visors a day.

Those kinds of numbers start to put a dent in the massive demand for PPE from NHS medical practitioners and community workers (social care, food delivery, shop workers, posties, etc.)

I think I can find a location for assembly and I think I can reach out to find volunteers (for example students are sitting around doing nothing).

It feels like to achieve this we'd need

- finalised design
- buy in by medical establishment
- straightforward build instructions

Then I can reach out and set the wheels in motion.

Is this a good idea? Can you help me?

**Comment by KarlDunkerley** [comment]
Hope mine is substantially less if we leverage the laser to cut the foams 100 at a time.
Reckon around 1-2 mins each.

**Comment by KarlDunkerley** [comment]
Ground floor would be good as we don't want to be lugging up and down stairs. 
500 sheets of a4 PVC 220 micron quite heavy and the boxes need to go back out as well.
Spacious so we can separate work tables.
Debatable is one person does all tasks on a visor or each person does a single task.
Health implications of multi-handling.
My design can all be done with gloved hands hence move away from velcro.

**Comment by ajlennon** [comment]
> Hope mine is substantially less if we leverage the laser to cut the foams 100 at a time.
> Reckon around 1-2 mins each.

Are you getting anywhere with medical feedback Karl ?

**Comment by KarlDunkerley** [comment]
Not yet as I am mainly passing them on to your and Ade etc.
I think it is best we all agree standards and who we are supplying.
I am in Southport with lots of care homes. The Liv Hospital is near DoES. Will also depend on quantities people want and how many vollies we can get.
My design is now ready and don't think I can substantially improve it. No PETG to be had. Using PVC/Acetate/Polyprop hence cutting shape manually 3-4 sheets at a time.
Two different staplers works well. One for foam thickness and one for elastic straps.

I'm pretty much ready to go.
Just need medical say so or talk to care homes I guess.

**Comment by ajlennon** [comment]
@amcewen is mad busy talking to NHS about designs today. WIll try to catch up with him and see what can be done

**Comment by afroleft** [comment]
Sample of one and I am a product manager with scars, but I'm mindful of swamping our little operation with coordination work. 

I think we should organise all of our attention and energy around getting our first batch shipped. 

We know what we need to do. We have production tools. We have money coming in. We are sourcing materials, let's get something out of the door into customers hands.

Adrian has a few friends that he knows and trusts in the region which makes sense to coordinate there. Let's say less than 10 people. Even that will still be a big coordination ask. Deliveries, reimbursements, progress tracking, assigning jobs, sharing ideas. 

Taking on more people requires more coordination and I wonder if do so, we'll only hamper our capacity to get behind one thing and do it very well. 

All of this is on a timeline of course. No reason to say we can't add more people on once we're systems up. Just important to me we walk before we run.

**Comment by ajlennon** [comment]
I agree - We don't want to be swamped. It seems like an effort like this should be setup separately as a parallel work stream

**Comment by KarlDunkerley** [comment]
Have posted the foam visor requirements on the github page. Hadn't spotted I had edit rights. Done.

**Comment by amcewen** [comment]
Totally agreed @afroleft.  Until mid-afternoon today we'd shipped more videos than visors.  Now we've shipped a handful more visors than videos.  Our video:completed-order ratio is currently 4:0.

Not that the videos aren't good and useful, but we haven't delivered on any of our promises until that 0 changes.  That's what I'm focusing all of my efforts towards.  @ajlennon even setting up "separately as a parallel work stream" will take up time from some of the team and it's currently tiny.

Ask me again next week and my answer might well be different, but until that 0 changes...

**Comment by ajlennon** [comment]
>Not that the videos aren't good and useful, but we haven't delivered on any of our promises until that 0 changes. That's what I'm focusing all of my efforts towards. @ajlennon even setting up "separately as a parallel work stream" will take up time from some of the team and it's currently tiny.

I understand that you're 150% on the design work but on day one this stream has the potential to deliver 20,000 units so it's worth some of my time imho

**Comment by KarlDunkerley** [comment]
Am already cooking up ready to do proper production at weekend. Have cut 100s of foam strips in day.
Cut up elaccy strips and knocked off a couple of dozen in half an hour.
Plenty of samples.
Reckon on around 200 a day per person.
Probably better for someone with dexterity greater than a demented chimp.
Nearly there.

**Comment by ajlennon** [comment]
> Am already cooking up ready to do proper production at weekend. Have cut 100s of foam strips in day.
> Cut up elaccy strips and knocked off a couple of dozen in half an hour.
> Plenty of samples.
> Reckon on around 200 a day per person.
> Probably better for someone with dexterity greater than a demented chimp.
> Nearly there.

I'm more than happy to try to put some time into this with you Karl. Big question in my mind is have we had NHS sign off?

**Comment by KarlDunkerley** [comment]
That's still the $64,000 question...

**Comment by ajlennon** [comment]
>That's still the $64,000 question... 

Have you spoken to anybody?

**Comment by KarlDunkerley** [comment]
Well I have the materials so am happy to meet at Does for a session on Saturday.

**Comment by ajlennon** [comment]
> Well I have the materials so am happy to meet at Does for a session on Saturday.

Maybe we can find somebody in the NHS then?

**Comment by KarlDunkerley** [comment]
I'm not sure duplicating the effort is worth hence bouncing the FD of the LHCH on to Ade.
I'm just going to produce. Have the gear. Spent the money.
Might as well be ready. Could always sell them to public for a couple of quid to raise money for NHS etc.

**Comment by ajlennon** [comment]
>I'm not sure duplicating the effort is worth hence bouncing the FD of the LHCH on to Ade.

What's being duplicated?

**Comment by KarlDunkerley** [comment]
Am going to drop some off at local surgery and maybe a care home.
How is fundraising coming on?

**Comment by afroleft** [comment]
We’re working with probabilities not absolutes.

Adrian went to NHS procurement teams yesterday and they have ordered. 

That’s enough of a sign off for me at this stage.

**Comment by KarlDunkerley** [comment]
Are we doing a video call again tonight?

**Comment by KarlDunkerley** [comment]
Adrian, have you made contact with the lady across the road who has a fabric workshop? Lily somthing or other???
She may have usefool tools and working space for the foam visors if we can get a group together.
Maybe her staff would be interested instead of sitting at home.
Thoughts?

**Comment by KarlDunkerley** [comment]
Has anyone discovered for definite if UV Light kills the virus and what kind of exposure is needed?

**Comment by AdamFloyd** [comment]
> @KarlDunkerley, @AdamFloyd and others have been coming up with exceptional "no print/cut" designs which could in my understanding be assembled by hand by volunteers.

I'm sorry but I have absolutely no idea why I am tagged in this. I am a software developer, I don't know any of these people and have had nothing whatsoever to do with design or manufacture of visors. It's a great cause but entirely outside my area of expertise so this must be a case of mistaken identity. I am not the person you're looking for so please stop tagging me in this discussion.

**Comment by ajlennon** [comment]
Apologies @AdamFloyd - my mistake! No more tagging

**Comment by amcewen** [comment]
@KarlDunkerley I' haven't spoken to Try and Lilly yet, but they're involved in the parallel gown/mask initiative with Mary Lamb (who's downstairs from them) detailed in #29.  Given their main business involves staff cutting and sewing fabric, that seems a more productive use of their kit than visors.

**Comment by SayBeano** [comment]
> 
> Has anyone discovered for definite if UV Light kills the virus and what kind of exposure is needed?

Between 200 and 300nm UV light spectrum is needed but I've seen between 200 and 250nm said to be the optimum.

The process is called ultraviolet germicidal irradiation. Every nook and crany needs to be exposed.

Further details : https://en.wikipedia.org/wiki/Ultraviolet_germicidal_irradiation#Method_of_operation

> The effectiveness of germicidal UV depends on the length of time a microorganism is exposed to UV, the intensity and wavelength of the UV radiation, the presence of particles that can protect the microorganisms from UV, and a microorganism's ability to withstand UV during its exposure. 

Effectively the longer the better and the more encosed / sterile the environment the better.

My knowledge is that the process, however effective has a high cost to entry though someone with working-knowledge may know better

**Comment by KarlDunkerley** [comment]
I was thinking they may have some spare equipment such as scissors and may be able to help setting up a small prod line given that's what they do.




    On Thursday, 2 April 2020, 10:55:32 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 


@KarlDunkerley I' haven't spoken to Try and Lilly yet, but they're involved in the parallel gown/mask initiative with Mary Lamb (who's downstairs from them) detailed in #29. Given their main business involves staff cutting and sewing fabric, that seems a more productive use of their kit than visors.

**Comment by KarlDunkerley** [comment]
Thanks for that. V useful.

    On Thursday, 2 April 2020, 11:09:02 BST, Mark Sabino <notifications@github.com> wrote:  
 
 



Has anyone discovered for definite if UV Light kills the virus and what kind of exposure is needed?


Between 200 and 300nm UV light spectrum is needed but I've seen between 200 and 250nm said to be the optimum.

The process is called ultraviolet germicidal irradiation. Every nook and crany needs to be exposed.

Further details : https://en.wikipedia.org/wiki/Ultraviolet_germicidal_irradiation#Method_of_operation


The effectiveness of germicidal UV depends on the length of time a microorganism is exposed to UV, the intensity and wavelength of the UV radiation, the presence of particles that can protect the microorganisms from UV, and a microorganism's ability to withstand UV during its exposure.


Effectively the longer the better and the more encosed / sterile the environment the better.

My knowledge is that the process, however effective has a high cost to entry though someone with working-knowledge may know better

**Comment by SayBeano** [comment]
Again on UV, FWIW. A spectrum analyser should be employed to validate any UV light source.

I have no idea how this done though.

**Comment by KarlDunkerley** [comment]
Is there a call tonight? Anyone got a link?

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by KarlDunkerley** [comment]
Latest costings using Acetate. Even cheaper with 140micron..
    On Thursday, 2 April 2020, 10:55:32 BST, Adrian McEwen <notifications@github.com> wrote:  
 
 


@KarlDunkerley I' haven't spoken to Try and Lilly yet, but they're involved in the parallel gown/mask initiative with Mary Lamb (who's downstairs from them) detailed in #29. Given their main business involves staff cutting and sewing fabric, that seems a more productive use of their kit than visors.

**Comment by plastictactics** [comment]
Closed as these handmade visors expose DoES to additional CE Marking risk, whereas we have reached customer acceptance, good production rate, and have CE Marking opportunity for the hybrid v1 4-hole design.

**Comment by ajlennon** [comment]
> Closed as these handmade visors expose DoES to additional CE Marking risk, whereas we have reached customer acceptance, good production rate, and have CE Marking opportunity for the hybrid v1 4-hole design.

No - we have a CE marking opportunity for a variant of the design with Prusa hole spacing

**Comment by plastictactics** [comment]
Ah right, thanks for the clarification.
