### ISSUE TITLE
Orders are coming through 💪  What’s next?

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#38]
This will need teasing apart in to multiple threads. 

Orders are coming through + the donations are gathering momentum [(link)](https://www.gofundme.com/f/get-visors-into-the-hands-of-healthcare-workers). Some questions: 

1. What daily throughput of visors can we get reach at DoES? 
2. @ajlennon + @amcewen  + @moorst and I have access to the source of truth spreadsheet for orders, does anyone else want access? nudge me?
3. There are lots of people saying they can produce with their 3d printers at home / schools etc, are we planning on aggregating them? (specifically, assigning them to jobs, reimbursing them for materials)?
4. @DuncanNisbet is working on leads for plastic, I linked AstraZenica to @amcewen for materials, where are for materials? Do we need to order more? We can draw down from the GoFundMe as and when we need. Will need to coordinate with Mazen, project CFO. 

Looking to the request / dispatch flow, it looks like there are a few key Jobs to be done: 

1. Notify people their request has been received
2. Assigning a job to a maker (i.e. DoES, or School)
3. Tracking progress
4. Notifying requester of dispatch 
5. [IF] requester has mentioned they can pay, our handsome CFO @mjamjoum can draw up an invoice to get funds back in  

I have a friend who is happy to help with this. 

Am I missing anything?

**Comment by ajlennon** [comment]
fwiw I am starting to engage with schools via @ka81. They have a different set of needs to makers. Assuming we can progress will probably spin this out into a separate issue.

**Comment by Moorst** [comment]
I've added a quantity field 👍

**Comment by plastictactics** [comment]
Closed as the initial questions have been answered in other threads, and the jobs either have people assigned or aren't required based on current workflow.
