### ISSUE TITLE
Tell funders what their donation amount will specifically afford

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/covid19#39]
https://twitter.com/arthrowl/status/1245323435422728193

> Could you estimate a unit cost? Might help people rationalise their donation, e.g. "my money will pay for 10 visors, neat"

I don't know if Arthur has a Github account, so I'm making this issue on behalf of him.

This is a great idea. Once we're sure of the real pricing structure for our production, we should let people know what their £10+ donations are going to achieve. Whether £10 will get us 100 visors, for example. 

I worked out in #4 that a standard 1KG reel of filament is around £17, and will afford us, conservatively, 90~ visors. Once this has been proven in the real world, we should let people know on the gofundme that £17 = 90 visors. 

This was based on the Verkstan design, which I'm unsure if is valid to use at this point still.

The same should be applied to all of the other things we're capable of producing, once we find out for sure.

**Comment by plastictactics** [comment]
There are some unit costs in FaceShield.md [here](
https://github.com/DoESLiverpool/covid19/blob/master/FaceShield.md) but I get the impression they are early estimates.

I understand that some progress has been made on purchasing raw materials for the visor headbands today - once production starts we'll be able to calculate a reasonably accurate figure for marketing.

^arthur
