### ISSUE TITLE
Work out how to set printers up as a production line

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#4]
@MatthewCroughan has suggested that we set up the 3D printers so we can have them knock the finished print off the bed and start the next, so they'll run as a production line to start new prints when no-one is around.

We should work out how to do that, and jot down the steps so we can set up other printers to do that too.

**Comment by MatthewCroughan** [comment]
What I'm aiming to do is have gcode files available for people with a given known printer model to be able to use. E.G if you own an ender 3 this gcode file will:

 - Print the model
 - Home at the end of the print
 - Drop down to `Z0` at a safe point
 - Push the part off as safely as possible towards the front of the printer

It will do this for as long as there is filament. Perhaps we can make a safe gcode file that does this only 60 times, as that's about what you can make with the current non-prusa designs on a 1KG reel of filament:

Assuming 16g is the weight of the unit, `1000 / 16 = 62.5 visors`

**Comment by MatthewCroughan** [comment]
Work on this will begin shortly after Alex arrives with a 1mm nozzle that I require for testing, as the 3d printing approach is far less feasible with a nozzle size of 0.4mm, which more than doubles the print time.

**Comment by MatthewCroughan** [comment]
The print guide here for one of the candidate visors is very informative. 
https://3dverkstan.se/protective-visor/protective-visor-print-guide/

It suggests we can:
 - Remove all infill
 - Use a layer height of 0.6mm
 - Use up to a 1.2mm nozzle

All of which means we can save on weight and speed up print time to 10-15mins. 

Assuming the print time is 15 mins and weight is 10g, that means we have a much more optimal print and can get around 96~ visors out per printer, per day.

`1440 mins in a day / 15 mins per print = 96 visors per day`
`1000g /10g = 100 visors per reel`

**Comment by amcewen** [comment]
Nice, but that looks like a comment that should live over on #5 :grinning:

**Comment by MatthewCroughan** [comment]
@amcewen Didn't see that, will remove it and move it over.

**Comment by plastictactics** [comment]
Where's this up to @MatthewCroughan? Are we still doing the 3D printed designs?

**Comment by amcewen** [comment]
Our 3D printing efforts have mostly been superseded by the laser-cut approach, so we don't need to optimise things on the 3D front.
