### ISSUE TITLE
Customer requests for 3DVerkstan mods

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#42]
One of our first two orders is for 220 of the [3DVerkstan](https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/3d-printed/3DVerkstan/Visor_frame_EUROPE_80mm_4hole_v1.stl) model.

@mdunschen any chance you can do me a stacked version of that, so I can leave it running overnight?  (The 7-stack of Prusa's seemed to work fine!)

Each one takes ~44 minutes, so I guess a stack of 16 (assuming that's less than 20cm high) would be good.

A stack I can stick on tonight would be awesome...

Then, they also had a bit of feedback on some improvements they'd like - if we could fill in the recess in the top of it so it's easier to clean, and ideally make the curl at the end of the arms a bit more open - again to make it easier to get in to clean, that would be great.  The source for the design is [Faceshield.nu](http://faceshield.nu), but I couldn't spot anything other than STL files for it...

**Comment by mdunschen** [comment]
@amcewen: I can stack it, but I need to put some sort of supports in
between, right? Little cylinders like in the Prusa stack. The Prusa stacks
have something around the front toggles, I don't think I can replicate that
easily, but maybe the cylinders will be enough. I will try now, but I am
not sure aobout you being able to stick it on tonight, it's been a long day
for me. I will let you know.

**Comment by MatthewCroughan** [comment]
@mdunschen I'd like to request that if you are making that, can you also accomodate a 0.6mm layer height as well as a 1mm diameter nozzle?

**Comment by ajlennon** [comment]
@amcewen I have an order for 12x3 masks. They want to know what we are charging?

**Comment by mdunschen** [comment]
Matt, I'm not sure what that means. The height of one frame is 5mm, I put a
support layer of 0.25mm in between, that's what I've copied from the prusa
stack. Of the layer height is 0.6, fits that mean that the space between
each frame has to be bigger than 0.6mm? Can now easily be done with my
python script if needed.

**Comment by MatthewCroughan** [comment]
Brilliant! I'm happy to experiment from here with this. I'm currently working out all the caveats of printing with a 1mm nozzle, afterwards I'll attempt to use your script to generate a stack for this nozzle. 

Yes, I think the support layer would have to be 0.6 + 0.05, I'm assuming the previous layer height in use by Adrian was 0.2 or so. Is that why you've chosen 0.25?

Also, I had no idea you could manipulate STLs using Python like this, so I'm going to learn a lot of from figuring out the manner in which you've approached this. 

Thanks so much Martin.

**Comment by mdunschen** [comment]
Ok, it looks like you know what you're doing. I wanted to move the code to
a more appropriate location. It was quickly hacked and a lot of redundant
code with the stacking I did for the Prusa model. You'll see the commit no
doubt.

**Comment by MatthewCroughan** [comment]
@mdunschen Indeed. Just woke up as my sleep schedule is ruined, however I'm going to give this design a go in an hour or two. 

Just in case you didn't know, you can tag issues in your commit messages so they'll show up in this webpage. For example, if your commit message contained "#42" it would show up here.

**Comment by mdunschen** [comment]
@amcewen and Matthew: I've added a version of the verkstran design with the
mods Adrian asked about: Bigger loops at the end and a filled in shield
above the forehead. It might not be positioned well, but let me know what
you think.

**Comment by mdunschen** [comment]
Ah file is this one:
https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/3d-printed/3DVerkstan/DoES_Verkstran.stl

**Comment by wwaites** [comment]
Hi. We have made a factory centred around the Edinburgh Hacklab with a good process to do this design together with continuous printing (http://the.earth.li/~martin/temp/ultimaker-pushoff.webm) on a few kinds of printer. With some tooling and up-front effort, the theoretical maximum throughput of a printer is about 120/day. We evaluated a few designs and the verkstand was preferred by the medics in the Borders and Lothian. Have functioning supply lines into local hospitals. We're spinning up copies of the factory at the University of Edinburgh.

**Comment by amcewen** [comment]
@wwaites Nice!  How did you get the continuous printing going?  It'd be good to get the same running on our Ultimakers

**Comment by wwaites** [comment]
@amcewen https://www.edinburghems.com/gcode/

Documentation is lagging and being curated. But basically it's:

1. big nozzle
2. a block that fixes to the extruder assembly to push
3. start cooling the bed when printing is half-way done
4. some custom g-code to push

There's some work to combine this with stacking which may make it more reliable and reduce babysitting.

**Comment by wwaites** [comment]
To be clear, *I* am not responsible for this cleverness. It was Martin Ling and Costa Talalaev who came up with it.

**Comment by ajlennon** [comment]
@wwaites I was talking to Ondrej at 3DCrowd just now on the coordinators meeting. He tells me that you have prints down to 11 minutes? WOW. Are you supplying 11 minute prints to the NHS Scotland?

**Comment by ajlennon** [comment]
^^^ @MatthewCroughan 11 minute prints. Can you test this on your setup?

**Comment by wwaites** [comment]
Yes, we are. I think we may have had to slow them down slightly for consistency, but still sub-20 minutes.

**Comment by MatthewCroughan** [comment]
@wwaites Lets take this over to #5 i have some questions :)

**Comment by plastictactics** [comment]
Closed on understanding that this initial order has been filled, and we are not getting more requests for this design.

**Comment by ajlennon** [comment]
Just had this in from 3DCrowd

![image](https://user-images.githubusercontent.com/1537834/79234983-ef9a8f00-7e62-11ea-8e71-fa54edc4bcfe.png)
