### ISSUE TITLE
Centralising requests for PPE

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#43]
Flagging a bit this end but wanted to highlight some of the operations groundwork that's going on. 

@zarino and @JackReason85 have setup a workflow for orders in the DoES Team Trello. [Link](https://trello.com/b/OlVA4eN2)

<img width="1779" alt="Screenshot 2020-04-01 at 19 57 43" src="https://user-images.githubusercontent.com/1761311/78175614-12847680-7453-11ea-8b47-232bb7df71ac.png">

We are currently working on a first come first served basis. Might want to change this down the road and look at prioritising based on clinical impact/need but that opens and shit ton of questions and right now, want to keep questions to a minimum.

@amcewen can you email me the orders that you have and the dates that they were made? 

Anyone else who has had verbal requests, please email them to covid@doesliverpool.com 

For each order, we need the information that's set out here in the request form. [Link](https://docs.google.com/forms/d/e/1FAIpQLScV9-SxioO0zpePppJy86g2vq6njRXdCcN2OLRbQvkOypAOcg/viewform)

Keep peddling 👍🏼

**Comment by ajlennon** [comment]
@afroleft  I suggest we move this over to 3DCrowd for Prusa masks. They have a good setup coming online and it frees us up hopefully?

**Comment by zarino** [comment]
@ajlennon I assume you mean https://www.3dcrowd.uk? Looks good.

Is there a way to volunteer the laser-cut masks via 3D Crowd too, or is it only for the 3D printed ones?

And do you know _when_ their order management system is likely to come online? If it’s not imminent, then we should probably continue with whatever we can cobble together in the meantime, since it looks like we already have orders to fulfill.

**Comment by afroleft** [comment]
If we are deciding against the local plans that we leaned to the other day [(link)](https://github.com/DoESLiverpool/covid19/issues/25#issue-590175326), then I need a clear plan not just fizzing ideas:

1. What happens to orders?
2. How do we coordinate with their production schedule? (and I mean end to end coordination operation plan)
3. What's the message to the people who have funded us so far? We're now working nationally, not regionally? 
4. Are we producing the same standard as them @amcewen can you shine a light on this?
5. How are they dispatching jobs to local producers?
6. Do we have any evidence they have shipped anything useful? 
7. My friend was 8th to order from them (nearly 2 weeks ago), and has only just received her order. Instead of visors, she just got visor head bands. 
8. I am finding it difficult to coordinate on a local level, are we confident that we can pile on and coordinate on a national level?

**Comment by amcewen** [comment]
We have 0 orders for the Prusa mask so far, fwiw, only from a sample size of 2, admittedly.

@afroleft both of the orders I know of are in Trello.

My gut feel is that running things locally makes more sense, keeping the feedback loops tighter.

**Comment by ajlennon** [comment]
@zarino Yes they are pulling together an excellent national platform - standardised designs, processes for manufacture and critically tracking, and logistics. They also have the legals to address liabliity issues.

They are currently *only* working with Prusa RC3 masks which we agreed a couple of days to print.

If there are any orders for Prusa  masks then I suggest they are routed through their system

They want to engagee on laser cut and they want faster prints and in future will want to engage on the alternative print designs @amcewen has taken orders for.

We can't route those orders throught them at present through so they will need to be handled locally

**Comment by ajlennon** [comment]
@afroleft no change - still acting locally and engaging nationally as that's the way to effect the most good for the most people.

- I suggest all Prusa RC3 orders go through their system
- All local 3D print makers are directed to 3DCrowd.uk
- We carry on with our own alternative print and laser cut designs for our own local orders until they are in a position to leverage our work
- We use their legals to limit our liability
- We use their SOP and their tracking to ensure we're delivering to the safest degree we can

I am coordinating with them for the North West so you are welcome to route through me, although I'm shortly going to need help.

**Comment by afroleft** [comment]
> @afroleft no change - still acting locally and engaging nationally as that's the way to effect the most good for the most people.

> I suggest all Prusa RC3 orders go through their system
> All local 3D print makers are directed to 3DCrowd.uk

@ajlennon fair enough. Are we not 3D printing at DoES? 

I am being a focus bitch just to get us to a point where we ship—please try not to hate me:)

Once we're systems up, it will make sense to look further out for ways to collaborate with more people.

**Comment by ajlennon** [comment]
@afroleft - yes. Underwater now. Can we put in a Zoom this evening and I'll try to explain where I'm coming from. I don't see things as either/or, just doing what's most effective.
