### ISSUE TITLE
Capture footage for DoES PPE visibility/marketing

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/covid19#44]
This is a follow up issue. I will be editing any footage submitted together to produce marketing material that looks nice.

Ideally if your phone can, record in 4k. Message me if possible to get access to a Nextcloud instance in order to submit footage of a substantial filesize.

You can also ping me on twitter @MatthewCroughan in order to contact me, or email me at matthewcroughan@protonmail.com, alternatively message @ajlennon who will forward things to me.

---

thanks @MatthewCroughan — deffo want to capture some footage of the production and dispatch to healthcare workers. 

That would give prospective donors more confidence in donating to us.

_Originally posted by @afroleft in https://github.com/DoESLiverpool/covid19/issues/33#issuecomment-606806995_

@ajlennon I mean in the coming days and weeks. 

We'll need footage of:
 - Multiple 3d printers in action
 - People processing items
 - Dispatching of the items
 - Hygiene procedures
 - Planning and documentation occurring 
    - For example. An over the shoulder of Adrian planning out a page on github, at his desk.
    - Paper work printed off that shows a guide for procedures

Stuff like that. If anyone thinks of more scenarios and footage that would be good to add, perhaps we should make a new issue to store it.

_Originally posted by @MatthewCroughan in https://github.com/DoESLiverpool/covid19/issues/33#issuecomment-606868446_

---

**Comment by ajlennon** [comment]
Will do - underwater at the moment - keep prodding me
