### ISSUE TITLE
Increase laser cut production

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/covid19#48]
Everything is in place to produce more of the laser cut designs from DoES 
Sourcing materials #21 has been an issue but we should have sufficient to make in greater numbers. It would be good to work out a rota to safely keep the machines running as much as possible.

The three stages are;

- Laser cutting headbands - This is the slowest part of the process so keeping the machine supervised as much as possible is the most important part (Or utilising other cutters identified in #46)

- Cleaning - Both parts of the headband need cleaning in IPA to remove staining. 

- Face visor -  There is some A4 sheet suitable which just needs four holes punching and the corners rounded. The remaining material is on a roll and needs cutting into A4 sheets first. It's a quick process and we have ~250 in stock just from this afternoon

All three stages are set up in separate areas but obviously it's important not to have crowds in at the same time.

**Comment by wwaites** [comment]
Hi. Our group (https://edinburghems.com/) has looked at various laser-cut designs. We have access to various laser cutters both at the Edinburgh Hacklab and at the university. One significant bottleneck is getting the plastic film off. That's slow and fiddly. Do you have any advice on a good way to do that?

**Comment by ajlennon** [comment]
^^^ @amcewen ?

**Comment by amcewen** [comment]
@wwaites our designs are cut from polypropylene, which tends not to come with a film on it, so it'd not something we've had much trouble with.

**Comment by plastictactics** [comment]
Our laser is ready to go.

Once the material arrives we will collect the plastic, cut it, then drop off 'raw' product to be dropped in just before the cleaning process at DoES - as opposed to cleaning the parts and supplying them sterile. Can look at setting up a 'clean room' on our end if cleaning becomes a bottleneck in production at DoES.

Once we've got to grips with the process, I think I can pull enough people in (not connected to DoES) to keep the machine going most hours of the day.

**Comment by plastictactics** [comment]
I have been in touch with Steve who represents Lydiate Learning Trust [https://twitter.com/lltppe]. They are producing their own visor design and delivering them through their own channels, but have run out of material.

I'm cautiously assuming that our project can supply them with material even though their product won't go to meet our order list - how would we account for this material? Is this the remit of @mjamjoum?

**Comment by ajlennon** [comment]
I've got a number of SMEs who need material. Can we align on what to do about that @plastictactics @mjamjoum @jackreason85 @DuncN

**Comment by plastictactics** [comment]
Can I arrange collection from DoES yard for the PP sheet material please? Laser sitting idle. 07857 904 804. Thanks! @ajlennon are you on site today and able to open up the shutters?

**Comment by ajlennon** [comment]
> Can I arrange collection from DoES yard for the PP sheet material please? Laser sitting idle. 07857 904 804. Thanks! @ajlennon are you on site today and able to open up the shutters?

This is from the mammoth pile Adrian got in? Sure I am here now. What time?

**Comment by plastictactics** [comment]
Am trying to arrange something for around 6pm - will you be there that late?

Rough estimates to figure out how many sheets to take on this run: ~60 minutes per sheet including handling. 24hrs for 7 days would be 10,080‬ minutes, which would be 168 sheets. We won't achieve 24hrs ever day but I think we could get through 100 sheets in the next week or so. Sound reasonable?

**Comment by ajlennon** [comment]
@plastictactics sounds good to me. I'll stay until about six then or when Jackie arrives. Jackie should be here around six.

**Comment by plastictactics** [comment]
Closing since there is a more active and focused version of this discussion over at #72.

Note that the latest decision on this is that laser cutting outside of DoES is only to happen where the third-parties (like us) are:
- Making the visors that Liverpool Heart and Chest Hospital has already accepted;
- Using materials already purchased by DoES; and
- Doing it a volunteer basis
