### ISSUE TITLE
Optimise 3D print design for speed of printing

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#5]
Looks like we'll be printing either the Spanish or the Prusa design on the 3D printers.  We should work out how quickly we can print them, so we can get more printed.

**Comment by amcewen** [comment]
I'm currently printing one of the Spanish design (in baby blue PLA), with the settings they recommend:

Here's the recommended printer settings:
- Nozzle:  0.4mm to 0.8mm
- Layer Height : 0.3mm
- Base and top layers 3
- Wall thickness 3
- Infill 20%, triangular
- No support
- Print Speed: Operator to decide

With the 0.4mm nozzle the print time is 56 minutes

twitter@Concreted0g tells me in N Wales they're choosing the similar-to-the-Spanish one over the Prusa:
> I think we are leaning towards the other one. It's hard to justify the Prusa print time for us. 2hr 30 at 0.35 on a 0.4 nozzle compared to 30mins on the same setup for the other one. Both work over ff3 [the standard masks the NHS staff wear]

**Comment by MatthewCroughan** [comment]
The print guide here for one of the candidate visors is very informative. 
https://3dverkstan.se/protective-visor/protective-visor-print-guide/

It suggests we can:
 - Remove all infill
 - Use a layer height of 0.6mm
 - Use up to a 1.2mm nozzle

All of which means we can save on weight and speed up print time to 10-15mins. 

Assuming the print time is 15 mins and weight is 10g, that means we have a much more optimal print and can get around 96~ visors out per printer, per day.

`1440 mins in a day / 15 mins per print = 96 visors per day`
`1000g /10g = 100 visors per reel`

**Comment by amcewen** [comment]
Just noting that we should chat to [our contacts at Create Education](https://twitter.com/CREATE_EDU_PROJ/status/1243321430072229889) to get the Ultimakers up and running smoothly, for the prints tuned for them.

**Comment by ajlennon** [comment]
fwiw - I am reading on the Covid19 slack that there are logos and such on the Prusa design. They are suggesting taking off any twiddly bits to improve print time

**Comment by MatthewCroughan** [comment]
I saw the comments about the stacking design in #15. This design would likely be most optimal on a stock ender3 or ultimaker, as the cooling down of the bed is necessary for automated removal. It would add quite some time (3-4 mins) before the part un-adheres from a regular glass bed allowing for removal by bashing the head up against it. 

This should also only be performed on clean glass beds with no adhesive. I'll have the gcode for this on an ender 3 up and running today and show a demo video of it. I've had a few mishaps relating to bed adhesion, much to my dismay and initial ideas. 

If we want to make this not-an-issue and speed it up a bit more, we need to get something like the Anycubic Ultrabase. 
https://all3dp.com/1/anycubic-ultrabase-review-glass-plate-print-bed/

>"Basically, the Anycubic Ultrabase a very sophisticated glass bed that provides better adhesion to prints, but at the same time, releases them very easily." 

The Anycubic Ultrabase is what is used in this video https://youtu.be/avlengYsJdw, which demonstrates how you can generate the toolpath required to remove a part from a 3d printer automatically, our goal here.

**Comment by amcewen** [comment]
Given your comments @MatthewCroughan and how well the stacked design seems to be printing, I'm wondering if the stacked approach is an easier way to solve the minimal-downtime-for-the-3D-printers problem.

@mdunschen would you be able to add another couple of visors to the stack?  The stack of 4 takes 10 hours to print, which is good, but if we could add another 2 or 3 to the stack that'd take it to a 15-17 hour print.  Then we could kick off a print at the end of the day, and it would run through to the morning when someone is back in to check on the printers.  Similarly if we could drop one of the visors from the stack so we've got a ~7.5hr 3-visor print then we could have a "day print" and a "night print" and that would keep the printers running non-stop without having to worry about new beds for them...

**Comment by MatthewCroughan** [comment]
@amcewen What I'm saying in short is that the stacked visors are better given the fact that the bed would need to cool down to remove them automatically without the aforementioned special bed. So the only manual step needed would be to collect a bag full of stacked visors and pry them apart. And of course restock the filament.

**Comment by mdunschen** [comment]
Yes, I'll get onto it now.

**Comment by mdunschen** [comment]
Actually this is not straight-forward: I cannot do this in Fusion because I would have to turn the STL into a body in order to edit. I think I will have to manipulate the STL file programmatically (find the triangles for the top, move these up by the height of one head band, then, copy the triangles of the headband below and move up by height of one stack) but I have the tools (reading and writing STL) to do it. But if somebody has the Brep of one head band It would be easy to do in Fusion. Then I would just have to add the support structure for the toggles. I'll go for the STL manipulation now.

**Comment by amcewen** [comment]
@mdunschen there seem to be STP files for the RC3 design on the Prusa site: https://www.prusaprinters.org/prints/25857-protective-face-shield-rc1/files

**Comment by mdunschen** [comment]
Done it with the STL, see the python scripts, and added one STL with 7 headbands stacked up. stackUp.py should be quite clear, the number of added stacks is hardcoded. Could be improved but I have to go now.

**Comment by ajlennon** [comment]
Hi @amcewen had this in from the Covid Slack - apparently there's an RC3.1 which is faster than RC3. Which are we currently on?

>@Alex Lennon - Coordinator - zNorthWestUK - Liverpool sorry was that the RC3 or RC3.1 because the 3.1 is faster (1 hr 20 mins per pcs) (edited)

**Comment by amcewen** [comment]
We're on the RC3, although we have no orders for it yet.  We have one order for 220 Verkstan though, so that's what we'll be printing for a while :-)

**Comment by mdunschen** [comment]
@amcewen have you been able to print the 7 stack? I was not 100% sure if
the support structure is right, it might have got blurred into the toggles.

At least maybe run it though the slicer?

**Comment by MatthewCroughan** [comment]
@mdunschen The design seems to look good. I can give a go at printing it out in a moment. Although I'm not sure how well this part will print with a 1MM nozzle. 

![image](https://user-images.githubusercontent.com/26458780/78159461-836b6480-743a-11ea-99b8-f7169658a9a4.png)

The production math for this part is as follows:

Line Width: 1mm Nozzle 
Layer Height: 0.6mm Layer 
Print Speed:  60mm/s
Print Time: 8 Hours~
Yield per job: 7 Visors
Automated Removal Time: 3 mins per job
Production Time per Job: Print time + Automated Removal Time (8.05 Hours)
Weight per job: 352G~


`24 / 8.05 = 2.98 jobs per day`
`352 * 3 = 1056g filament per day`
`7 * 2.98 = 20.86 visors per day`

**Comment by MatthewCroughan** [comment]
@amcewen In regards to your previous comment about "the minimal-downtime-for-the-3D-printers problem." It's not so much about the printer downtime. In fact, if you think about it, by using a design that only yields 21 visors in 24 hours, we're wasting 4.7x the electricity, since `100 / 21 = 4.76` Is it not possible we can stack the more efficient designs? It's not about keeping the printers running, it's about getting more jobs and units out within 24 hrs.

Also, I'm not trying to step on any toes, just trying to contribute, in the case that this comes across in a nasty way, which I do not intend.

**Comment by MatthewCroughan** [comment]
It is also worth noting that this design becomes a lot more viable once we have more 3D Printers as mentioned in #27 

For as long as we're going for designs that take hours to print rather than minutes, even with a 1mm nozzle, we will always be missing out on that 3-4x production time boost though. 

If we get lots of orders, the only way I can see us fulfilling them is by having more 3d printers available to use.

**Comment by MatthewCroughan** [comment]
This is what a design with the following parameters is beginning to look like. #42 

Layer Height: 0.6mm
Print Speed: 60mm/s
Nozzle Size: 1mm
Print Time: 15 Minutes
Infill: 0%

![IMG_20200401_211840](https://user-images.githubusercontent.com/26458780/78182805-c0495280-745e-11ea-852f-0ebdfdc8d295.jpg)

**Comment by MatthewCroughan** [comment]
Here is a top and bottom view of the newly printed part. There are some artifacts as a result of not having a hotend capable of full utilisation of the nozzle in terms of flowrate. This part is perfectly functional and I'm very surprised at how flexible and snap resistant it seems to be from my playing around with it.

The total print time was a bit under 15 minutes.


![IMG_20200401_213653_1](https://user-images.githubusercontent.com/26458780/78184668-c2f97700-7461-11ea-97b0-060186cb261c.jpg)
![IMG_20200401_213709_1](https://user-images.githubusercontent.com/26458780/78184682-c7259480-7461-11ea-9537-82fa7e1e3762.jpg)

**Comment by mdunschen** [comment]
This is the Prusa stack, @amcewen had asked me to make a stack for the
Verkstan Europe design which is in the 3DVerkstan folder. Apparently
there's an order for 220 of the Verkstan model.

**Comment by MatthewCroughan** [comment]
@mdunschen I think this issue is for general discussion and progress on the optimization of all models. If you like I can spin out a separate issue for the discussion of optimization of the Verkstan model, do you think I should?

**Comment by ajlennon** [comment]
![image](https://user-images.githubusercontent.com/1537834/78235694-edcee400-74d0-11ea-9a38-578596074fe0.png)

https://covid-19volunteersuk.slack.com/archives/C0105RQLMBL/p1585821485255000

**Comment by MatthewCroughan** [comment]
@wwaites I've had a lot of trouble printing at this rate with PLA. I've gotten a few prints off but it is really inconsistent. This is at a range of temperatures. 200 - 210 nozzle, 50-70 bed, everything in between. 

Do you find that PETG is necessary for this print to actually succeed on a glass bed? Mine just keeps warping in the corners, though sometimes it manages to stick and succeed. I've also compressed it further and further until it was too compressed, though this did not help with the adhesion to the bed.

**Comment by wwaites** [comment]
@MatthewCroughan you're asking me questions that I don't know the answer to. I am not the expert in this, but I'll send you an email putting you together with the people who are.

**Comment by MatthewCroughan** [comment]
Brilliant. I really appreciate that.

**Comment by amcewen** [comment]
Our 3D printing efforts have mostly been superseded by the laser-cut approach, so we don't need to optimise things on the 3D front.
