### ISSUE TITLE
Suppliers & Orders now in 1 spreadsheet

### ISSUE THREAD

**Issue by DuncN** [DoESLiverpool/covid19#51]
@ajlennon has put together a spreadsheet of suppliers we've contacted.
I've put together a list of orders we've made to some of these suppliers.

I've merged my sheet into Alex's so we have 1 location for suppliers & orders (on different tabs)

https://docs.google.com/spreadsheets/d/165ydLAv_HcAsAB7a8fG1qEOGcXx4beffEl95sK_pK_o/edit?usp=sharing

Thanks,

Duncs

**Comment by plastictactics** [comment]
Could you add 'estimated delivery' to the material supply, or have an inventory control sheet so we can track what's in the building? #47 says you're feeling poorly - would you like me to take some ownership over that role, or can you manage?

**Comment by DuncN** [comment]
Nice one, thanks for reaching out!

I've added order date & estimated delivery to the orders I know about in the "orders" sheet:
[PPE Suppliers](https://docs.google.com/spreadsheets/d/165ydLAv_HcAsAB7a8fG1qEOGcXx4beffEl95sK_pK_o/edit?usp=sharing) just to make sure we're in the same spreadsheet ;-)

That order sheet was meant to be the beginnings of an inventory control sheet, but it only has orders in it for now. Happy for you or anyone to update & improve!

RE offer of help - yes please! this role needs constant attention & requires more time than I can currently provide. I'll be putting a shout out in the Who's who thread shortly ([issue 47](https://github.com/DoESLiverpool/covid19/issues/47))

Duncs

**Comment by plastictactics** [comment]
Thanks for adding that.

@afroleft offered to call about the role but perhaps it's better for us to speak directly and save them taking the time. Could you give me a call on 07857 904 804 to discuss? It would be worse for me to overcommit and do a bad job than to stay out of it, so want to make sure I have enough capacity to do it before agreeing to the role. I may also be able to find someone else to fill it.

**Comment by plastictactics** [comment]
This is my first time using Github, so stupid question time: should we close this issue since it's done? Just mindful that the list of issues is getting longer - I'm getting a bit snowed under with it so likely to start missing useful information soon. Have engaged with another issue about who has the permission to do that (currently just the extremely busy people, I think). We can arrange the video call about the inventory role over in #47.

**Comment by ajlennon** [comment]
Just my 5c but if  you are doing this and you think it's done then I'd close it. Somebody else can easily open it if they need to. Nothing gets lost.

Also fwiw if there's a specific issue you're owning or co-owning to work on then you can click in the top right to add yourself (and anybody else relevant) as assignees.

Hope that's useful.

**Comment by DuncN** [comment]
Yeah, lets close it.

People will still be able to find the link to the spreadsheet (the main reason I created the issue - links were getting lost in other threads)

**Comment by DuncN** [comment]
Closing issue as it has served it's purpose of making the PPE supplier spreadsheet easier to find
