### ISSUE TITLE
Write up our packing note to go out with orders

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#56]
We need a packaging note to go in any shipments of visors, explaining that this isn't certified PPE but is a community-made cough/splatter shield (or similar).  Do we need any assembly instructions too?

As an example, this is what goes out in the 3Dcrowd orders: https://docs.google.com/document/d/1ipGBP1CCZsUscppO69OJKRDLRTV-3UveHzpW1vbnM-I/edit

**Comment by ajlennon** [comment]
The 3DCrowd one is good - they are putting a lot of work into considering liability

**Comment by afroleft** [comment]
@ajlennon you stay focused production, I'll pull this together. 

After the fun times over in #55, I'll need someone to roll their sleeves up and sign off on it. 

That does not mean sitting there quietly as plans take shape, and then complaining after we've shipped. 

@johnmckerrell would you be able to help here?

**Comment by ajlennon** [comment]
One thing for consideration is that 3DCrowd are specifically not calling these PPE Visors for liability reasons. It's something like "Splash protection shield" now or similar

**Comment by johnmckerrell** [comment]
Yes happy to review and sign this off

**Comment by afroleft** [comment]
> It's something like "Splash protection shield" now or similar

"If-someone-coughs-on-you-this-may-or-may-not-help-you-past-performance-is-no-indicator-of-future-earnings-shield" @ajlennon ??

**Comment by ajlennon** [comment]
> > It's something like "Splash protection shield" now or similar
> 
> "If-someone-coughs-on-you-this-may-or-may-not-help-you-past-performance-is-no-indicator-of-future-earnings-shield" @ajlennon ??

By jove I think he's cracked it! :laugh:

**Comment by afroleft** [comment]
Pulled together a [draft here](https://docs.google.com/document/d/1W8Vz0iEujy3rxH2b4yxsfkLYMkkhcg8tSsinFaqhjEU/edit?usp=sharing)

Just need the visors design name so I can add in assembly instructions. Fingers crossed we can get this over the line rapidly so Liverpool Heart & Chest can collect their first 200.

**Comment by johnmckerrell** [comment]
Made a tiny tweak but apart from that I think it's pretty good. It is very strong on its "THIS IS NOT PPE" message, I suppose one question would be - is that what people who are ordering it are expecting? Obviously we need to put this in to cover us, but we have to hope no-one will actually be put off by it, certainly don't want to waste any visors.

**Comment by afroleft** [comment]
> Made a tiny tweak but apart from that I think it's pretty good. It is very strong on its "THIS IS NOT PPE" message

Great—yes wanted to make that one loud and clear. 

Thanks for tightening that up John. If you're happy, I'm going to lean on you to DoES’ify the work that we're doing. 

Your feedback is precise and objective which keeps things moving.
