### ISSUE TITLE
First Order: Liverpool Heart & Chest

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#58]
Let's start with the good news. 

Just jumped off the phone with Dave from Liverpool Heart & Chest. He’s saying most of his consultants are coming back saying they much prefer the DoES Visor design over others. Especially surgeons, as sometimes they wear goggles with lights underneath their visors, so the way ours suspend away from the face is happy days. 

---

### Want to try and get this out the door tonight. Key points:

1. We do not have assembly instructions 
2. We are not charging Liverpool Heart & Chest since they are our first order and our customer service could have been better. 
3. Liverpool Heart & Chest are champing at the bit for visors _any help is a help_ and all that jazz
4. They are happy to assemble themselves and have teams ready to do this 
5. They are happy to come and collect from DoES 

### A move fast proposal: 

1. We wait for @JackiePease or Chris to show up at DoES. 
2. They nudge Dave to send people over. 
3. Jackie or Chris does a quick demo to bring the Liverpool Heart & Chest peeps up to speed on how to assemble
4. Dispatch with newly formed note here [link](https://docs.google.com/document/d/1W8Vz0iEujy3rxH2b4yxsfkLYMkkhcg8tSsinFaqhjEU/edit?usp=sharing)

Liverpool Heart & Chest’s Dave is more than happy with his and is above and beyond thankful for the help.

**Comment by JackiePease** [comment]
Fine - I can get there by 6. Is everything packed now?
________________________________

**Comment by ajlennon** [comment]
@JackiePease - I've been laser cutting all day. Haven't touched anything else.

**Comment by JackiePease** [comment]
@ajlennon would you be able to pack them now then?

**Comment by ajlennon** [comment]
Sorry @JackiePease I couldn't make the time. Been in meetings etc. etc. none stop

**Comment by plastictactics** [comment]
1. Assuming this has been shipped.

2. If so, let's celebrate it in over at The Daily #60!

3. And close this issue :)

**Comment by JackiePease** [comment]
Was waiting until we'd sent out the last 40 today!
________________________________
