### ISSUE TITLE
Make a decision on distribution 

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#6]
How are we going to distribute these? 

Looks like we have a number of options: 

1. Centrally through Clinical Commission Groups 
2. Centrally through Trust Procurement Teams 
3. Direct to healthcare workers through an informal request/fulfil 
4. Any combination of the above

**Comment by ajlennon** [comment]
fwiw we have Iain Hennessy, Clinical Director, Alder Hey Innovation Hub offering to assist,

>We really appreciate you reaching out to us. Visors are absolutely critical and there is a shortage nationwide. If you want to make them and we have too many then we could redistribute to other hospitals? Broadgreen just gave us a load of surgical masks. We think we have cracked it here – but things can always change. One of our solutions does rely on a long range supply chain.

**Comment by afroleft** [comment]
> Iain Hennessy, Clinical Director, Alder Hey Innovation Hub offering to assist

Excellent. Will close this off for now.

**Comment by afroleft** [comment]
@ajlennon I hear of a few GPs that are struggling for gear this morning. [Ruth](https://www.linkedin.com/in/ruth-ellis-25660815/), my former BD at Patchwork is linking me with a few that are in need. 

A lot of them work independently, so not under a centralised sourcing programme like Alderhey.

Would we be game for keeping a few around for individual GP requests?

**Comment by ajlennon** [comment]
That's not a decision I can make but my very strong feeling would be yes, and I am guessing that would be the consensus.

There was talk on the call last night about all the other needs, including those going into the community and those in schools and cleaning schools. This was discussed as being a lower priority than the medical professionals but still important.

I also believe we're looking at the idea of "hyper-local" production so it makes sense to me to be distributing what we can around here and to GPs where we have been contacted and told there's a need, and so forth, rather than shipping them off and hoping they might get used somewhere else

Just my  5c

**Comment by afroleft** [comment]
> I can make but my very strong feeling would be yes, and I am guessing that would be the consensus.

Great. 

Dumping this here but hearing that the PPE situation is nothing short of horrendous at Aintree. 

Asked a few people to confirm this for us. Will follow up. 

If so, would be great if we could coordinate with your man from Alder Hey to ship some over there too.

**Comment by magman2112** [comment]
Decided to reopen this issue as a few comments are hidden from the normal view on Github.

I have been in contact with my niece, who is a nurse in the HDU at the Walton Centre of Aintree hospital. She is going to talk to her manager tomorrow (Saturday)about these visors. They will also have someone from the supply team visiting them on Sunday to show them correct procedures for PPE, so we will get a mention then as well.

I will let you know if anything comes of it.

**Comment by ajlennon** [comment]
I've had various contacts today from local medical professionals. Am trying to undestand if anybody has a holistic local plan for who needs what. In the absence of that I am suggesting setting up a Google Sheet to capture this with local medical professionals and other workers who need PPE.

see: https://github.com/DoESLiverpool/covid19/issues/18

**Comment by SayBeano** [comment]
Just FYI that [this twitter](https://twitter.com/MedSupDriveUK) account exists

With the following information on a click through on the webby.

> We are an organisation of volunteers aiming to coordinate a nationwide effort to redirect unused PPE from non-healthcare related settings to the frontline where it is urgently needed the most.

There are links at the bottom of [this page](https://www.medsupplydrive.org.uk/donate) to donate.
