### ISSUE TITLE
What to do with offcuts from white PP

### ISSUE THREAD

**Issue by plastictactics** [DoESLiverpool/covid19#62]
I think I can find a good home for the white PP sheet scraps. Would be fantastic if the operator can bag it up as part of production process and keep it relatively clean (there will be soot of course).

@JackiePease would like some, I think - anyone else want a slice? Or have any other thoughts?

**Comment by drakard** [comment]
Hello. From what I have seen the current process (at least what I have followed) is to bag up all scraps larger than 1cm x 1cm separated by colour.

**Comment by amcewen** [comment]
Yep, that's now covered in the [Production Guide too](https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/production.md#laser-cutting-headbands)

I'm assuming we can close this and let your Plastics Playgroup lead on the recycling side when lockdown is over, @plastictactics.

**Comment by JackiePease** [comment]
As we're not expecting any more coloured PP at the moment, I've moved that over to the Plastic Playgroup crate.
