### ISSUE TITLE
Some upgrades to speed up PPE cutting

### ISSUE THREAD

**Issue by reasonPi** [DoESLiverpool/covid19#63]
I made some improvements to the existing PPE cutter.It only needs to align the plastic sheet with the edge of the template.It can get perfect right angle and very fast cutting speed.

Best regards
Yangshuo
![20200410_093614](https://user-images.githubusercontent.com/32732699/78977051-5b9d9000-7b0f-11ea-833f-43163d4ce8cb.jpg)
![20200410_093604](https://user-images.githubusercontent.com/32732699/78977060-5e988080-7b0f-11ea-94b3-100871b62423.jpg)

**Comment by ajlennon** [comment]
Great work @reasonPi - I'll be in shortly to help out

**Comment by plastictactics** [comment]
Closed on the understanding that this solution is now part of the standard procedure for making visors. Thanks Yangshuo!
