### ISSUE TITLE
What is the policy regarding disinfecting personal items brought to the space?

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#68]
For example laptops and phones.

**Comment by JackiePease** [comment]
I've been using soap and water to clean my phone, but that depends on whether you believe your phone is waterproof or not.We've been told that Dettox spray or wipes will kill the virus, and would seem to be a good choice for phones and laptops you have to bring into the space (I haven't been able to find any yet).On 11 Apr 2020 22:28, drakard <notifications@github.com> wrote:
For example laptops and phones.

**Comment by drakard** [comment]
@JackiePease Is there 70% isopropanol in the space?

**Comment by JackiePease** [comment]
There was - it's all been used up now. We're looking at using bleach solution for cleaning visors.
________________________________

**Comment by drakard** [comment]
@JackiePease Ok thank you

**Comment by amcewen** [comment]
Did we also use the three bottles that were still in the solvents cupboard (on Friday, I think)?

To the original question, I think that's now covered [in the contamination section of the Production Guide](https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/production.md#preventing-contamination-in-the-space)

**Comment by drakard** [comment]
@amcewen thanks
