### ISSUE TITLE
Live check in and check out sheet of who is in the space

### ISSUE THREAD

**Issue by goatchurchprime** [DoESLiverpool/covid19#74]
More useful than the calendar sheet is a live sheet saying what's going on right now, so I don't need to phone in on the robot to see who's there.

People should put in their check-in and check out times (arrival and leaving, and optionally when next going there) on the next sheet to the calendar:

https://docs.google.com/spreadsheets/d/1Nn2kCCu9TOgxJlUh01Y-L10jXJNEoijAkrV9hTZMpOo/edit#gid=1319346095

For maximum convenience, we could have this sheet open at all times on a public computer (eg the one attached to the vinyl cutter) and have a note on the door reminding people to mark it up.

**Comment by JackiePease** [comment]
That seems like a lot of hassle. Any quick way to update the doorbot system to allow check outs?
________________________________

**Comment by MatthewCroughan** [comment]
I've commented on this in #47, we should be using a regular calendar to see who's in the space right now.  Here's an example of a proposed calendar below.

![image](https://user-images.githubusercontent.com/26458780/79115486-d8ce3c80-7d7d-11ea-9025-c0676889cc37.png)

[A link to add this calendar to your google account, where you can add to it](https://calendar.google.com/calendar/b/1?cid=dDhudXZtM3IyMGs5NHVxM2FnZnRkN3RsdGNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ)

[A link to publicly see the spreadsheet without a google account](https://calendar.google.com/calendar/embed?src=t8nuvm3r20k94uq3agftd7tltc%40group.calendar.google.com&ctz=Europe%2FLondon)

**Comment by goatchurchprime** [comment]
Last 3 times I've come in there were about 6 people around and I wasn't at all needed.  The only other way to find out is to phone in, get a call, or dial in with the robot.  

Wasted journeys, or not really knowing when is a good time to head over is a good deal more hassle than filling in a check-in check-out document that I can have open.

Could we give it a chance for a couple of days to see if it works?  I could come in now and fill it in with who is there that I see now.

**Comment by plastictactics** [comment]
With the number of volunteers, including people new potentially new to DoES and allowing for people with low digital literacy, I expect only a very simple system will work. We have three systems emerging - spreadsheet rota, calendar, and live check in. Whatever the solution, I encourage us to reach a decision today and improve incrementally from there.

To that end please continue discussion in #69, which I have renamed to account for the things raised here.
