### ISSUE TITLE
DoES Visor Project > DoES PPE

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#77]
Looks like it's going to be a sensible move to stop calling it PPE from a liability perspective. With that, I thought about what the identity of the project could be. `Covid` sends a shiver down my spine, so putting this little fella out as a proposal.  

<img width="715" alt="Screenshot 2020-04-13 at 20 01 34" src="https://user-images.githubusercontent.com/1761311/79150991-975f8080-7dc1-11ea-89e9-70aba458e216.png">

If you're happy, I'll setup a redirect to `visors.doesliverpool.com` and will coordinate the change across social and website. 

Feedback welcome.

**Comment by Robotorium** [comment]
Nice logo, I like it

Op ma 13 apr. 2020 20:08 schreef Tom Darlow <notifications@github.com>:

**Comment by JackReason85** [comment]
spot on

**Comment by ajlennon** [comment]
Lovely. :heart: melting.

**Comment by JackiePease** [comment]
Wondering if it should say DoES Liverpool? I love the logo though

**Comment by afroleft** [comment]
> Wondering if it should say DoES Liverpool? I love the logo though

<img width="644" alt="Screenshot 2020-04-14 at 10 16 55" src="https://user-images.githubusercontent.com/1761311/79207938-45f2d800-7e39-11ea-940e-c32358612ed7.png">

@JackiePease

**Comment by JackiePease** [comment]
👍
________________________________

**Comment by afroleft** [comment]
@johnmckerrell can you point `visors.doesliverpool.com` at Netlify ?

**Comment by johnmckerrell** [comment]
Done.

**Comment by amcewen** [comment]
Nice!

**Comment by amcewen** [comment]
We'll need to update the packing note branding too

**Comment by afroleft** [comment]
Yes that’s a shout. 

Zarino named the little fella Vinnie. Vinnie the visor. 

I’m making us all tshirts :)

**Comment by amcewen** [comment]
I updated the logo on the packing slip I've been using locally, so have [checked that into the repo](https://github.com/DoESLiverpool/covid19/blob/master/DoES%20Visor%20Packing%20Slip.odt) so there's a copy to use there.
