### ISSUE TITLE
Campaign Videos

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#78]
A good friend of mine Steph, has managed to produce a number of videos to help explain the story to the outside world. 

We have doctors and nurses from across the UK explaining why visors are helpful and thanking the DoES community for the work we're doing. 

The password for all of these is: `DoES` 

🌟 Main Film for Crowdfunding/YouTube and Twitter (16:9)
https://vimeo.com/405847926 

Animation (16:9)
https://vimeo.com/406862947

Crowdfunding on socials (4:5 and subtitles) 
https://vimeo.com/407207945

Short version of main film for socials (4:5, only to be used after the main film has gone up, to reprompt campaign, or if social spend is behind it.)
https://vimeo.com/407213212

Thank yous (9:16, Instagram stories/FB Stories) 
https://vimeo.com/407208254

I have a contact at the BBC who wants to share these, but wanted to check with @johnmckerrell  before I ship anything. 

One downside, the freelancers that pulled these together have had to get back to other projects—so making big changes will be difficult. Might be able to squeeze in a minor edit with a pretty please.

**Comment by JackReason85** [comment]
All looks really good, great job!

**Comment by johnmckerrell** [comment]
These look fantastic, thanks to Steph for doing them.

Mentions of PPE of course but I imagine we're too late to avoid that (things like the hashtag, but I guess that's not "ours" anyway).

Very good, very glossy, might be worth mentioning when we put them out that someone did them for free, we haven't been spending money on them.

Final thing, in the vocals for the second one "Because these are generously opened sourced" would be better as "Because the designs are generously open sourced" but it's not vital given I imagine we can't get it re-recorded!

**Comment by DoESsean** [comment]
These are fantastic. Genuinely got a little emotional at the 'thanks' one, it definitely hits the right notes.

**Comment by MatthewCroughan** [comment]
Amazing to see. Just amazing. Nothing more to add.

**Comment by MatthewCroughan** [comment]
If the sources for the video projects are made available, I can work on adding or removing content if needed, since the timeline and hard work has already been done it's just a matter of adding clips at appropriate times.

**Comment by afroleft** [comment]
> Very good, very glossy, might be worth mentioning when we put them out that someone did them for free, we haven't been spending money on them.

@mcknut right there with you. 

Wanted to thank them when we share the videos anyway. We’ve essentially had £15k worth of production for free; producers, editors, animators all came together last week to work around the clock on this. Only fair to link back to them to say thank you + highlights people are helping us in different ways

**Comment by ajlennon** [comment]
Wow. :heart: :clap: :mask: - I don't have the right words to tell you how impressed I am.

I have known for a long, long time how privileged I am to have met the amazing people at DoES and to be able to share a space with them.

In this co-vid nightmare one of the good things to come out of it is that I've met a whole new bunch of people are are clearly just **amazing** at what they do.

Wow. :clap: :clap: :clap:

**Comment by JackiePease** [comment]
Nicely made videos - thank you to the people who put them together

**Comment by mjamjoum** [comment]
Brilliant!
