### ISSUE TITLE
Improvements to laser-cut polypropylene design

### ISSUE THREAD

**Issue by amcewen** [DoESLiverpool/covid19#8]
So this design...

![image](https://user-images.githubusercontent.com/108468/77773716-eb3c3c80-7041-11ea-8552-f2fd64e52ce8.png)

...could be improved.  This photo is the initial version, I've already made a few tweaks but still:

 * [x] the band against your head isn't very breathable.
 * [x] the sides go quite far back, compared to the Prusa design (now I've got a printed one of them to compare with).  Modding that would use less material and cut a tiny bit faster
 * [x] the band for the visor sits quite far out - almost twice as far as the Prusa design, and about 1-2cm further than the laser-cut acrylic design we've tried
 * [x] I've got an idea for better securing the "loose" ends of the bands together
 * [x] it would be good to be able to use the "4-hole-punched visor" design with it, as suggested in [this comment](https://github.com/DoESLiverpool/somebody-should/issues/1415#issuecomment-604313318) from @RussCoty

**Comment by amcewen** [comment]
Latest design has most things fixed.  

 * Needs some fine-tuning of the spacing of the visor hole-punch tabs (maybe they should also be mushroom shaped for more security?)
 * The ventilation on the headband probably takes too much material out
 * There seem to be some internal reflections on the visor when you're wearing it, but I can't tell if that's this design, or just the lights in here.

![image](https://user-images.githubusercontent.com/108468/77801204-4c7b0480-7070-11ea-88f7-6737fb3ce453.png)

It's a 2 minute cut now.

**Comment by amcewen** [comment]
The internal reflections seem to be down to having the visor further away from the face, as the Prusa design suffers from that too.  So I think it's more of a problem of having a sheet of plastic a few cm away from your eyes.

**Comment by ajlennon** [comment]
fwiw - I am reading on the Covid19 Slack that there are logos and such on the Prusa design. They are suggesting taking these off to speed up the print?

**Comment by amcewen** [comment]
A bunch of updates and revisions today:
 * When worn the ventilation holes in the headband were less comfortable than without them, so I've removed them.
 * Make the bands thinner, which helps with the loss of ventilation holes, but mostly to bring the bottom edge of the visor a few cm lower
 * Switched to horizontal tabs to secure the visor, as that works much better
 * I've added a simple single-stroke font version number (it's in a different colour, so is easy to omit if we want fastest possible cutting)

**Comment by JackiePease** [comment]
IThe Liverpool University design doesn't have logos, and I've seen that criticism on Twitter, but also noticed medical people saying that they need them to identify different versions - need to discuss in meeting perhaps.
________________________________

**Comment by amcewen** [comment]
I've added the flattening visor tabs back in, which greatly improves the internal reflections problem.  That's checked in as v2, and I think marks this finished.

Still needs checking with some medical folk, but we can create new issues for anything they find.
