### ISSUE TITLE
See if we can get the Filippo (Scan and Make) laser cutter going

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#86]
Fillipo from Scan and Make locally reached out to us

- he has loaned us his laser cutter (it needs to go back)
- originally it was going to one fo Coffee Dave's shops but it's here at DoES at the moment
- can we work out if we can make use of this
- if so is it possible to use it at DoES or should we move it elsewhere
- Dave can help move it but it can't go in his shops as the exhaust gasses would damage the premises, so we'd need to find another place

Fil tells me the software he uses to control it is this https://rdworks.software.informer.com/8.0/?fbclid=IwAR2yipiZl3iiwJYQLTy7MwIezqUYhNu7mYXISpFwxMplcS5lS1VjqY4fUMQ

@Sean-anotherone could you give us your expert opinion on the best way forward? Thanks!

**Comment by plastictactics** [comment]
We may have room and ventilation for a second laser cutter at our workshop 
if not possible to operate it at DoES.

**Comment by ajlennon** [comment]
Could be we have a plan!

**Comment by ajlennon** [comment]
Hey @Sean-anotherone - can we get together tomorrow to take a look at it ?

**Comment by Sean-anotherone** [comment]
An update :
The machine is all set up, it is actually a really well put together cutter from a mechanical viewpoint, although the tube is really dusty / smoke covered so it seems a bit unloved.
It is running on a small carbuoy of water, a bin full will be needed if it is to be used in anger.
Mirrors and mounts are pretty good quality too, but I was;t able to check the alignment as it barely leaves a scorch on the tape.

There is an issue however - the beam is really low on power.  

The tube "strikes" and glows, but even with a piece of ply placed directly in the beam in front of the tube (i.e. no mirrors in the path) the spot only chars very slowly.

This "feels" like the tube is used up, but I'm not certain about that, low power from the supply could also cause similar (the tube is struck with quite a high voltage a which then drops significantly once current is being pulled, it might be that the HV is high enough but it can deliver any power).

I did suggest that putting the tube from Sophia in this machine would both confirm the diagnosos and get it up & running while a replacement tube is awaited, but there is conflicting advice about the feasibility of this online (including from Q&A pages on some manufacturers sites) about the impact it can have running a 30W tube from a supply adjusted for a 60W tube - in short, I'm not prepared to take the gamble that it won't cook the tube prematurely.

Under all this there is of course the point that I might be missing something and with s aimple adjustment it will spring into life at full power - hence the recommendation below.

**I would recommend that the owner of the machine (or the principal operator if not the same person) be invited to take a look and advise the best way forward, I don't think I can safely do any more with it without that happening.   (by safely, I refer to £££ safely - the only immediate safety concern I had was a couple of light leak-paths and I have taped them up).**

If there is a fast answer I can be back tomorrow, or evenings through the week.


If the power issue can be resolved, a full alignment check will be needed (it has been moved) and a larger reservoir for cooling water (tapwater will be fine, the water here is about 3-4 Mohm/cm, lab grade water is around 18 so the dielectric strength isn't an issue, but it would grow algae if used for a long time)

Sean-anotherone

**Comment by ajlennon** [comment]
Hi @Sean-anotherone - the awesome guys from Scan and Make - Francesco and Fil - have ordered a replacement tube. Should be arriving 27th

**Comment by ajlennon** [comment]
Got a new tube here @Sean-anotherone if you fancy taking a look :-D

**Comment by Sean-anotherone** [comment]
I'll come over tomorrow.  Has anyone seen a traffic warden anywhere nearby,  i.e. is it "safe" to part on Kempston st?
Sean
    On Saturday, 25 April 2020, 13:09:48 BST, Alex Lennon <notifications@github.com> wrote:  
 
 


Got a new tube here @Sean-anotherone if you fancy taking a look :-D

**Comment by ajlennon** [comment]
I've been parking  out the front for days and had no trouble yet. Touch :evergreen_tree:

**Comment by JackiePease** [comment]
@Sean-anotherone has fitted the new tube and the machine appears to be working. @ajlennon has got the information we need to set the z-height and provided it to @Sean-anotherone. 
This hasn't moved on, as we don't seem to need the laser cutter as much as we did at the moment.

**Comment by JackiePease** [comment]
The laser cutter is working and back with Filippo

**Comment by ajlennon** [comment]
Thanks very much Jackie!
