### ISSUE TITLE
Feedback: 3 out of 70 Misscut at Liverpool Heart & Chest

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#88]
Digging stuff out of huge cc chains from Liverpool Heart & Chest: 

> 70 has been distributed and 3 have been miss-cut on the laser printer meaning they can’t be put together. With that small sample, their current failure rate of `4.2%`.

![42f2f064-fe8f-4189-805e-d4da030d0dc8](https://user-images.githubusercontent.com/1761311/79463388-b2640780-7ff0-11ea-8b3c-69af2b3d2eb6.jpeg)

For now, I've explained that photos help us zero-in on the problem. 

Setup this [(link)](https://www.dropbox.com/request/Z3MlnkXiBiMwgI1TCvRr) up, they are sharing across the Trust. 

## **Where do we want to capture customer feedback like this?** 

My go-to would be Trello, where I can kanban, enforce wip limits, attach email history, shuffle order, assign people, mark reminders dates for follow up. 

Alternatively we can use GitHub issues.

**Comment by JackiePease** [comment]
I wonder if we should be putting them together
________________________________

**Comment by ajlennon** [comment]
> I wonder if we should be putting them together

We'd have to ask the NHS but my thought on that is if they are santising them before use (which I think they are?) then isn't it easier for them to do that if they aren't assembled?

**Comment by amcewen** [comment]
More people have access to github than Trello.  Github would let us tie any design changes back to the issue, which would be good for tracking the reasons for changes.

Putting them together would make them *lots* bulkier to ship around, and for hospitals to store them (plus require more volunteers) :thinking: 

There is often a bulge when you first assemble it, and you then smooth it out firmly to get rid of the bulge and secure the clear plastic.  Maybe as a first step we could try some assembly instructions and/or a video showing how to put one together?

**Comment by plastictactics** [comment]
I'm working on a more compact design with some other changes that I hope 
will be improvements - did they specify which cut was faulty? Can't figure 
it out from the photo.

**Comment by afroleft** [comment]
> More people have access to github than Trello. Github would let us tie any design changes back to the issue, which would be good for tracking the reasons for changes.

Good.

@amcewen so for now I'll capture feedback here tagged `customer feedback` with the following:

1. Who reported it (will tally if multiple people)
2. Number of times a customer has hit the problem
3. Description of problem
4. Photos if submitted

Anything I am missing?

Conscious of these piling up, so would be good if we can keep a handle on them and close them off as they are resolved.

**Comment by amcewen** [comment]
I *think* that this problem is solved if people know about `step 7` in the [assembly instructions](https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/instructions/visor%20instructions%20(2).pdf).  Not quite sure how we communicate that in order to close it though...?
