### ISSUE TITLE
Feedback: 2 Customers asking for assembly instructions

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#90]
We avoided this for our first order that went to Liverpool Heart & Chest because Jackie spent time with the team that picked the visors up to show them how to assemble. 

2 customers today asked for assembly instructions. 

Over in #88 @amcewen asked: 

> Maybe as a first step we could try some assembly instructions and/or a video showing how to put one together?

@MatthewCroughan is this something you might be able to help us with?

**Comment by JackiePease** [comment]
On 16 Apr 2020 16:33, Tom Darlow <notifications@github.com> wrote:
We avoided this for our first order that went to Liverpool Heart & Chest because Jackie spent time with the team that picked the visors up to show them how to assemble.
2 customers today asked for assembly instructions.
Over in #88 @amcewen asked:

Maybe as a first step we could try some assembly instructions and/or a video showing how to put one together?

@MatthewCroughan is this something you might be able to help us with?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

I have alread my emails Gina to see if she'd do this - she said she would, but up to you?

**Comment by afroleft** [comment]
> I have alread my emails Gina to see if she'd do this - she said she would, but up to you?

Bearing in mind we have 2 customers who are currently stuck, I'd suggest whoever can do it first 😅

**Comment by afroleft** [comment]
As a work around, I've sent over the product photos [link](https://www.dropbox.com/sh/lr7sco65vnlefjw/AADX9YqjeX7pNsSE7BuL-AQqa?dl=0)

**Comment by plastictactics** [comment]
Starting point from similar design by someone called Smokey: https://drive.google.com/file/d/1DXJn-i9RNlD1JACIlOTxQB5uEYw0-ryn/view

And they also made a video: https://www.youtube.com/watch?v=FT3pfzjqE-c

Found at: https://community.andmirrors.co.uk/t/covid-19-laser-cut-face-shield/168/170

I have added some etched markers to my development design with the hope that it makes assembly a little easier - feedback on attached welcome. 
[hybridV3_dev-snapshot202004161741.pdf](https://github.com/DoESLiverpool/covid19/files/4488614/hybridV3_dev-snapshot202004161741.pdf)

**Comment by afroleft** [comment]
> I have added some etched markers to my development design with the hope that it makes assembly a little easier - feedback on attached welcome.
hybridV3_dev-snapshot202004161741.pdf

@plastictactics  bingo!

**Comment by Robotorium** [comment]
I put together some IKEA style instructions. It's a bit of a rush job, but
specifically for the DoES design.

Op do 16 apr. 2020 om 20:32 schreef Tom Darlow <notifications@github.com>:

**Comment by Robotorium** [comment]
Sorry, apparently Chris H was still editing and I PDF'd too soon...
shareable link is
https://docs.google.com/document/d/1xS-EnIV1nsS5AiKfVBUyOwexYEo3Z4gSv7a1cMmBmCg/edit?usp=sharing

Op vr 17 apr. 2020 om 16:57 schreef Snoof Hattersley <snoofers@gmail.com>:

**Comment by afroleft** [comment]
> Sorry, apparently Chris H was still editing and I PDF'd too soon... shareable link is https://docs.google.com/document/d/1xS-EnIV1nsS5AiKfVBUyOwexYEo3Z4gSv7a1cMmBmCg/edit?usp=sharing Op vr 17 apr. 2020 om 16:57 schreef Snoof Hattersley <snoofers@gmail.com>:
> […](#)

I have a doctor here now @Robotorium. Will see how they get on and feedback.

**Comment by afroleft** [comment]
Ok feedback. Feedback visor instructions:

## Step 2 
Can we make clear that you need to firmly wriggle the small band through the whole?

![image](https://user-images.githubusercontent.com/1761311/79599309-2a0f6080-80dd-11ea-9d83-3250becc7912.jpeg)

## 5 
Little bit of confusion about how to feed in the strap into the headband piece. Wonder if a zoomed in version of that instruction might help?

![image](https://user-images.githubusercontent.com/1761311/79599339-35fb2280-80dd-11ea-8c84-2b4812338dd3.jpeg)

## Last step 
Would be a good idea to have an illustration of the completed visor to give clarity of the finished product. 

![image](https://user-images.githubusercontent.com/1761311/79599374-46130200-80dd-11ea-9240-a19159af8a0e.jpeg)

Personally fucking love this illustration style. How’d you do this?

**Comment by ajlennon** [comment]
Is this @Robotorium ? Yay Snoof! One criticism: No cute narwhal?

**Comment by Robotorium** [comment]
Thanks, I drew it :) would normally be a little less shonky but I only had
a couple of hours cause I was hoping to get something to be included with
the 5 o'clock shipment.

I've added in the step 2 instructions that it needs some firm wriggling.
Step 5, I'm not sure how much more zoomed in it gets without losing all
context. Would it maybe work if I added an arrow like the ones in your
screencap, and another one in the zoomed out view of the headband?

I'll draw the final product now, let me know about step 5?

Cheers.

And Alex, somewhere I have the very barest bones of a narwhal-based Unity
game that might conceivably get finished one day if I don't get distracted
every five minutes... But probably doesn't help the NHS so much.

Op vr 17 apr. 2020 18:58 schreef Tom Darlow <notifications@github.com>:

**Comment by afroleft** [comment]
@Robotorium let me know what you think. Once happy, nudge me. I will add to dispatch sheet and link up on website.

**Comment by afroleft** [comment]
> Would it maybe work if I added an arrow like the ones in your
screencap, and another one in the zoomed out view of the headband?

Yes thought that as I sent it 👍🏼

**Comment by amcewen** [comment]
@Robotorium it's ace, thanks!  And it did make it into the 5pm shipment.  The other order that got packed today is actually only going out midday Sunday, so I'll include whatever the latest version is then.

**Comment by Robotorium** [comment]
Thanks Adrian, glad I got there just about in time :)

Right, I've updated the google doc, I've also exported it as a PDF which
I'm attaching here. I have to go cook some tea for my eldest now, if anyone
wants to make a less shonky file out of it I'm also attaching all the
pictures. Let me know if you need anything else?

Op vr 17 apr. 2020 om 19:53 schreef Adrian McEwen <notifications@github.com

**Comment by afroleft** [comment]
@Robotorium top banana, brother ! thank you 

> And it did make it into the 5pm shipment

    ⚾️

**Comment by Robotorium** [comment]
Sister :) Thanks Tom, glad I could help.

Op vr 17 apr. 2020 om 20:12 schreef Tom Darlow <notifications@github.com>:

**Comment by huffeec** [comment]
Have added all the images and a pdf of the instruction sheet in the repository under the cut files.
https://github.com/DoESLiverpool/covid19/tree/master/visor-designs/laser-cut/instructions

**Comment by amcewen** [comment]
We've been shipping instructions in the orders for the past six days, so presumably can close this now?
