### ISSUE TITLE
Fixing volunteer onboarding

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#91]
Looks like our onboarding for volunteers needs some key improvements. 

## Areas we're looking to target: 
1. People saying they've reached out to volunteer but no one following up 
2. No central list of volunteers to mark off who has/has not been followed up with
3. Unclear from the Rota Spreadsheet what roles are technical/non-technical 
4. People confused, so we might need a little bit more hand holding through the various steps
5. covid@ email is just flooded with volunteers

Spoke with @zarino about cleaning up some of these issues. 

Better to assume prospective volunteers have no knowledge, so we want to answer questions: 

What is this project? 
➥ How can I get stuck in? / What stuff am I able to do?
➥ Given my availability, when I can I come and help out?
➥ What can I do to prepare beforehand?
➥ On the day where do I show up?
➥ Who do I contact on the day? 

Just sticking this here to let you know we're aware of this, and cooking up a set of improvements. //cc @JackiePease

**Comment by dfaligertwood** [comment]
Given I'm stuck at home for another week and a bit, I would be happy to help with answering emails/online admin if that would help. No worries if not.

**Comment by JackiePease** [comment]
Hi @dfaligertwood - that sounds excellent. I'm discussing procedures with @zarino later and will get back to you after that.
Update: @zarino is going to get back to me with new forms and I should be able to update you tomorrow

**Comment by ajlennon** [comment]
Coffee Dave is setting up a contact phone line with people answering. Could be something to leverage here?

**Comment by zarino** [comment]
I’ve created a volunteering form at https://docs.google.com/forms/d/e/1FAIpQLSca6bWcUwvAfzfc2A-vNTZklxa5KxeChzk6gO2pMnESX3pfCg/viewform, which posts responses into a spreadsheet. 

The form is signposted prominently at the top of https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/production.md, and it’s replaced @afroleft’s typeform links on https://visors.doesliverpool.com.

The idea is that, as offers come in to the spreadsheet, @JackiePease (or @dfaligertwood!) can send the volunteer an email, to arrange a date for them to come in for onboarding. And over time, the spreadsheet will also act as a database of volunteer details. We can add new columns if there are new things we want to (manually) record about each person.

One thing we’ll need to consider (and maybe change the form to accommodate) is that, previously, @afroleft’s typeorm was very open-ended, so you could use it to signal your intention to, say, help us 3D print stuff from your home. Whereas our new volunteering form is much more about coming in to DoES and performing one of the three pre-defined tasks. So we might want to update the form to include a way for people to express their interest in helping in _some other way_ than just coming in to DoES and cutting / cleaning visors.

**Comment by afroleft** [comment]
Nice step forward @zarino — thank you for tackling this one. 

Shall I update the production.md to link to this form? 

That should save us from the waves of unstructured email responses from volunteers.

**Comment by SayBeano** [comment]
This seems like the place to note that `pabb85` on twitter is currently off to Neston to get elastic for PPE he's preparing on 3D printers. Though I am not aware on the focus of 3D production support - I see them on the promotional videos that've released.

He's completed a form but would appreciate linking in with being able to supply his efforts to the the DoES hub and take on any materials that can be provided.
