### ISSUE TITLE
Improve our supply and distribution capability

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#94]
I am using these "Issues" rather like forum "topics". If people would prefer me to collect this information some other way please tell me and I will be happy to move it.

**Comment by drakard** [comment]
DPD were offering free delivery service for 3D Print UK. https://www.dpd.com/group/en/2020/04/07/dpd-uk-provides-free-delivery-service-to-supply-3d-printed-face-shields-to-national-health-service/

I couldn't see the official details for getting this service but if I do see them in the Slack I will add them here.

Edit: corrected information based on @ajlennon 's info.

**Comment by drakard** [comment]
Visor Bikes https://visor-bikes.com/ is a service run by Blood Bikes staff I believe for delivering visors. They operate in the North West covering our area so they seem like an ideal partner. Possibly they would also be willing to collect urgent incoming deliveries like the laser cutter spare part Jackie had to collect recently.

**Comment by ajlennon** [comment]
@drakard - we need to be a little bit careful here. DoES has it's own PPE effort going on and it's not part of 3D Crowd. DoES is kindly hosting a local 3DCrowd hub for packing and distribution of 3D Printed Prusa based visors but what DoES provides is different (laser-cut DoES design) and DoES is providing to our own order fulfilment.

So we have great links with 3DCrowd, and my hope is we can work ever more closely, but we're separate work flows at this time.

**Comment by ajlennon** [comment]
@drakard also to the best of my knowledge that DPD free delivery offer was for "The Big Print" weekend to a central depot and does not currently apply to 3D Crowd orders.

We should _definitely_ be talking to Blood Bikes etc. though

**Comment by drakard** [comment]
I checked and it looks like @ajlennon is correct the DPD service is no longer applicable.
